// SPDX-License-Identifier: GPL-3.0-only
/**
 * loc_00ca — dispatch a computed jump-table target back into a call.
 * DK routes most per-frame control flow through inline jump tables: a caller loads a selector and
 * a shared trampoline jumps to the little-endian target word beside the code. This is the far end.
 * The listed targets are a whitelist, not a range check — the game has neither: a selector that
 * walks off its table or picks a zero slot would dispatch plausible-looking garbage, so refusing
 * names it. The tables' null slots are the out-of-range case and are deliberately absent below.
 * LIVE-OUT: the dispatched handler's return value, forwarded — the difficulty guards among the
 * targets return a keep-going boolean their caller consumes as an early return.
 */

import { NotImplemented } from "../../../boards/dkong/io.js";
import {
  POWER_ON_INIT_ADDR, RUN_ATTRACT_STATE_ADDR, DISPATCH_CREDITED_SUBSTATE_ADDR, DISPATCH_IN_GAME_SUBSTATE_ADDR, CONFIGURE_FLIP_SCREEN_AND_SELECT_SUBSTATE_ADDR, RESTORE_PLAYER_1_CONTEXT_ADDR,
  ARM_TWO_PLAYER_BOARD_SETUP_ADDR, RESTORE_PLAYER_2_CONTEXT_ADDR, LOC_0A1B_ADDR, COMPOSE_SCREEN_AND_ADVANCE_SUBSTATE_ADDR, CLEAR_SCREEN_AND_SELECT_INTRO_ADDR, DISPATCH_INTRO_CUTSCENE_STEP_ADDR,
  BUILD_HOW_HIGH_SCREEN_ADDR, BUILD_BOARD_WHEN_TIMER_EXPIRES_ADDR, SEED_MARIO_ACTOR_RECORD_ADDR, RUN_DEATH_ANIMATION_SUBSTATE_ADDR, LOSE_PLAYER_1_LIFE_ADDR, LOC_1344_ADDR,
  LOC_138F_ADDR, LOC_13A1_ADDR, LOC_13AA_ADDR, SELECT_PLAYER_1_CONTEXT_ADDR, SELECT_PLAYER_SCREEN_OR_ATTRACT_ADDR, RUN_BONUS_ITEM_VALUE_DISPLAY_ADDR,
  DISPATCH_BOARD_CLEARED_INTERLUDE_ADDR, CLEAR_SCREEN_AND_SELECT_SUBSTATE_ADDR, RUN_GAMEPLAY_FRAME_ADDR, RESTART_ATTRACT_DEMO_AT_25_M_ADDR, COMPOSE_ATTRACT_TITLE_SCREEN_ADDR, CLEAR_SCREEN_AND_ADVANCE_SUBSTATE_ADDR,
  LOC_07CB_ADDR, CLEAR_SUBSTATE_WHEN_TIMER_EXPIRES_ADDR, RUN_ATTRACT_DEMO_FRAME_ADDR, ENTER_CREDIT_SCREEN_ADDR, COMMIT_GAME_START_ADDR, SETUP_INTRO_CUTSCENE_STEP_ADDR,
  RUN_INTRO_CLIMB_STEP_ADDR, ANIMATE_INTRO_CLIMB_STEP_ADDR, LOC_0B06_ADDR, LOC_0B68_ADDR, RUN_INTRO_ROAR_STEP_ADDR, ADVANCE_SEQUENCE_STEP_WHEN_TIMER_EXPIRES_ADDR,
  BEGIN_MARIO_DEATH_ANIMATION_ADDR, STEP_MARIO_DEATH_ANIMATION_ADDR, LOC_12DE_ADDR, BEGIN_KONG_RECAPTURE_INTERLUDE_ADDR, STAGE_NEXT_KONG_POSE_WHEN_HOLD_EXPIRES_ADDR, STAGE_KONG_CLIMB_POSE_ADDR,
  BEGIN_50_M_KONG_RECAPTURE_INTERLUDE_ADDR, DISPATCH_KONG_WALK_FRAME_ADDR, CLIMB_KONG_FIGURE_AND_BREAK_HEART_ADDR, ADVANCE_BOARD_STEP_WHEN_SPRITES_CLEARED_ADDR, ADVANCE_TO_NEXT_BOARD_ADDR, LOC_17B6_ADDR,
  STEP_SPRITE_ANIMATION_SEQUENCE_ADDR, LOC_186F_ADDR, LOC_1880_ADDR, RUN_RIVET_BOARD_FINALE_THEN_ADVANCE_LEVEL_ADDR, SEARCH_25_M_OBJECT_OVERLAP_ADDR, SEARCH_50_M_OBJECT_OVERLAP_ADDR,
  SEARCH_75_M_OBJECT_OVERLAP_ADDR, SEARCH_100_M_OBJECT_OVERLAP_ADDR, LOC_3110_ADDR, LOC_311B_ADDR, LOC_3126_ADDR, LOC_3131_ADDR,
  LOC_3E99_ADDR,
} from "./names.js";

// Every target the wired inline jump tables vector to; one reached by two tables is listed once.
const DISPATCH_TARGETS = new Set([
  POWER_ON_INIT_ADDR, RUN_ATTRACT_STATE_ADDR, DISPATCH_CREDITED_SUBSTATE_ADDR, DISPATCH_IN_GAME_SUBSTATE_ADDR, CONFIGURE_FLIP_SCREEN_AND_SELECT_SUBSTATE_ADDR, RESTORE_PLAYER_1_CONTEXT_ADDR,
  ARM_TWO_PLAYER_BOARD_SETUP_ADDR, RESTORE_PLAYER_2_CONTEXT_ADDR, LOC_0A1B_ADDR, COMPOSE_SCREEN_AND_ADVANCE_SUBSTATE_ADDR, CLEAR_SCREEN_AND_SELECT_INTRO_ADDR, DISPATCH_INTRO_CUTSCENE_STEP_ADDR,
  BUILD_HOW_HIGH_SCREEN_ADDR, BUILD_BOARD_WHEN_TIMER_EXPIRES_ADDR, SEED_MARIO_ACTOR_RECORD_ADDR, RUN_DEATH_ANIMATION_SUBSTATE_ADDR, LOSE_PLAYER_1_LIFE_ADDR, LOC_1344_ADDR,
  LOC_138F_ADDR, LOC_13A1_ADDR, LOC_13AA_ADDR, SELECT_PLAYER_1_CONTEXT_ADDR, SELECT_PLAYER_SCREEN_OR_ATTRACT_ADDR, RUN_BONUS_ITEM_VALUE_DISPLAY_ADDR,
  DISPATCH_BOARD_CLEARED_INTERLUDE_ADDR, CLEAR_SCREEN_AND_SELECT_SUBSTATE_ADDR, RUN_GAMEPLAY_FRAME_ADDR, RESTART_ATTRACT_DEMO_AT_25_M_ADDR, COMPOSE_ATTRACT_TITLE_SCREEN_ADDR, CLEAR_SCREEN_AND_ADVANCE_SUBSTATE_ADDR,
  LOC_07CB_ADDR, CLEAR_SUBSTATE_WHEN_TIMER_EXPIRES_ADDR, RUN_ATTRACT_DEMO_FRAME_ADDR, ENTER_CREDIT_SCREEN_ADDR, COMMIT_GAME_START_ADDR, SETUP_INTRO_CUTSCENE_STEP_ADDR,
  RUN_INTRO_CLIMB_STEP_ADDR, ANIMATE_INTRO_CLIMB_STEP_ADDR, LOC_0B06_ADDR, LOC_0B68_ADDR, RUN_INTRO_ROAR_STEP_ADDR, ADVANCE_SEQUENCE_STEP_WHEN_TIMER_EXPIRES_ADDR,
  BEGIN_MARIO_DEATH_ANIMATION_ADDR, STEP_MARIO_DEATH_ANIMATION_ADDR, LOC_12DE_ADDR, BEGIN_KONG_RECAPTURE_INTERLUDE_ADDR, STAGE_NEXT_KONG_POSE_WHEN_HOLD_EXPIRES_ADDR, STAGE_KONG_CLIMB_POSE_ADDR,
  BEGIN_50_M_KONG_RECAPTURE_INTERLUDE_ADDR, DISPATCH_KONG_WALK_FRAME_ADDR, CLIMB_KONG_FIGURE_AND_BREAK_HEART_ADDR, ADVANCE_BOARD_STEP_WHEN_SPRITES_CLEARED_ADDR, ADVANCE_TO_NEXT_BOARD_ADDR, LOC_17B6_ADDR,
  STEP_SPRITE_ANIMATION_SEQUENCE_ADDR, LOC_186F_ADDR, LOC_1880_ADDR, RUN_RIVET_BOARD_FINALE_THEN_ADVANCE_LEVEL_ADDR, SEARCH_25_M_OBJECT_OVERLAP_ADDR, SEARCH_50_M_OBJECT_OVERLAP_ADDR,
  SEARCH_75_M_OBJECT_OVERLAP_ADDR, SEARCH_100_M_OBJECT_OVERLAP_ADDR, LOC_3110_ADDR, LOC_311B_ADDR, LOC_3126_ADDR, LOC_3131_ADDR,
  LOC_3E99_ADDR,
]);

export function loc_00ca(m, target, site = "the NMI game-state table") {
  // A rewritten handler is invoked directly, not through the routine table: that is how the
  // call-bracket seam recognises a computed dispatch. Going through the table would open a frame
  // this dispatch never opened, and the seam would balance a bracket that is not there.
  if (m.overrides && m.overrides.has(target)) return m.overrides.get(target)(m);

  if (DISPATCH_TARGETS.has(target)) return m.call(target);

  throw new NotImplemented(
    `handler at ROM 0x${target.toString(16).padStart(4, "0")} ` +
      `(reached via rst 0x28 table at ${site})`,
  );
}
