#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Time Pilot gameplay pixel gate: JS render vs MAME, through coin -> start -> play. Attract takes
no input, so a golden captures itself and proves little; this drives the same tape into both.

THE TAPE OFFSET IS +1, MEASURED. Both tapes press at frame 400; the first frame the coin alters RAM
is JS 401 and MAME 402, 13 bytes each side. Discriminating: at +1 the state diff is byte-for-byte
over all 1802 frames, at +2 it fails at 402. Re-derive if the tape's timing changes.
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(GAME))
sys.path.insert(0, os.path.join(REPO, "tools"))

import numpy as np  # noqa: E402
import pixel_gate  # noqa: E402
from framediff import FROZEN_OFFSET  # noqa: E402
from hardware import Hardware  # noqa: E402

HW = os.path.join(REPO, "boards", "timeplt", "hardware.json")
DRIVER = "timeplt"
SECONDS = 30
GOLDEN_FRAMES = 1802          # floor(60.0 * 30) + 2, the capture's own length

# ★★ THE SHARP CRITERION, because the loose one has no teeth: a live wrong twin (one bit flipped in
# the shape byte `refreshSpriteFromHeading` stores, changing 630 of 1801 frames) reaches only 2.99%
# and PASSES the 5%. Below BAND_FROM a correct layer is nearly exact -- 31 of 1566 frames, worst
# 33px, against 408 frames / 490px for that twin. BAND_MAX_PX is 3x the CORRECT layer's floor, NOT
# fitted to the twin; scroll-pace and bar-phase twins also go red here.
BAND_FROM = 113
BAND_MAX_PX = 100

LUA_COIN, LUA_START = 400, 500
TAPE_OFFSET = 1               # measured; see the module docstring
HOLD = 8

LANDMARK = 235
GEN_OFFSET = LANDMARK + 1

DIFF_FROM = 0

# ★★ WHAT THE IDIOMATIC PATH COSTS, SO A PASS IS NOT READ AS PARITY. (1) The first GEN_OFFSET
# golden frames are NOT compared -- boot produces none on a yield clock, and rendering further
# cannot extend coverage: the length is golden_frames - offset. (2) A scanline-compositing residual
# above BAND_FROM, because MAME paints as the beam descends while a yield clock snapshots FINAL RAM
# for every row. ⛔ SO ROWS 0..BAND_FROM-1 ARE WEAKLY GUARDED -- a HOLE, not an artifact: only the
# 5% covers them and the residual spends 2.309% of it, leaving ~1543px/frame of slack. Injected
# top-band defects all PASS with the band unmoved at 33px (one tile 2.420%, one sprite 2.755%, FOUR
# sprites 4.095%), so a top-of-screen regression under ~1500px is invisible here.

INPUT_LATCH = 0xA9AE   # raw IN0 mirror, rewritten every NMI: 0x01 coin held, 0x08 start held
COIN_TAKEN = 0xA981    # 0 -> non-zero when the machine ACCEPTS the coin (debounced rising edge)
PLAY_ACTIVE = 0xAD30   # explicit flag: stored 0xFF when play begins, cleared with xor a


def lua_tape(path):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"""-- Generated by pixel_suite.py -- coin then 1P start on IN0.
local IN0 = manager.machine.ioport.ports[":IN0"]
assert(IN0, "no :IN0")
local coin, start = IN0.fields["Coin 1"], IN0.fields["1 Player Start"]
assert(coin and start, "missing Coin 1 / 1 Player Start")
local f = 0
_G.__pt = emu.add_machine_frame_notifier(function()
  f = f + 1
  coin:set_value((f >= {LUA_COIN} and f < {LUA_COIN + HOLD}) and 1 or 0)
  start:set_value((f >= {LUA_START} and f < {LUA_START + HOLD}) and 1 or 0)
end)
""")
    return path


def capture_golden(rompath, out, tape):
    subprocess.run(
        [sys.executable, os.path.join(REPO, "tools", "mame_golden.py"),
         "--hardware", HW, "--lua-dir", os.path.join(HERE, "lua"),
         "--rompath", rompath, "--out", out, "--seconds", str(SECONDS),
         "--tape", tape],
        check=True)


def band_worst(js_rgb, golden_rgb, offset, from_frame):
    """Worst per-frame pixel count in rows BAND_FROM.. , and how many frames are over budget."""
    w, h, bpf = pixel_gate.screen_geometry(HW)
    n = min(os.path.getsize(js_rgb) // bpf, os.path.getsize(golden_rgb) // bpf - offset)
    worst, over, worst_at = 0, 0, None
    with open(js_rgb, "rb") as jf, open(golden_rgb, "rb") as gf:
        for i in range(from_frame, n):
            jf.seek(i * bpf)
            gf.seek((i + offset) * bpf)
            a = np.frombuffer(jf.read(bpf), dtype=np.uint8).reshape(h, w, 3)[BAND_FROM:]
            b = np.frombuffer(gf.read(bpf), dtype=np.uint8).reshape(h, w, 3)[BAND_FROM:]
            c = int(np.any(a != b, axis=2).sum())
            if c > BAND_MAX_PX:
                over += 1
            if c > worst:
                worst, worst_at = c, i
    return worst, over, worst_at


def runtime():
    """Which layer the player runs, read from the manifest rather than assumed."""
    r = subprocess.run(
        ["node", "-e",
         f'import("{os.path.join(GAME, "manifest.js")}").then(m => console.log(m.default.runtime))'],
        capture_output=True, text=True, check=True)
    return r.stdout.strip()


def render_js(out, frames, idiomatic):
    cmd = ["node", os.path.join(HERE, "render.js"), "--frames", str(frames),
           "--input", f"0xc300=0x01@{LUA_COIN + TAPE_OFFSET}:hold{HOLD}",
           "--input", f"0xc300=0x08@{LUA_START + TAPE_OFFSET}:hold{HOLD}",
           "--frames-out", out]
    if idiomatic:
        cmd += ["--idiomatic", "--tape-origin", str(LANDMARK)]
    subprocess.run(cmd, check=True)


def state_column(golden_dir, addr):
    """Every frame's value of one work-RAM cell, read out of the golden's state dump.

    Geometry comes from the same hardware.json the capture used, which already checks its
    regions sum to the declared frame size -- so a layout change cannot silently mis-index.
    """
    regions = Hardware.load(HW).state_regions
    frame_bytes = sum(size for _n, _b, size in regions)
    off = 0
    for _name, base, size in regions:
        if base <= addr < base + size:
            off += addr - base
            break
        off += size
    else:
        raise SystemExit(f"pixel_suite: 0x{addr:04X} is not in any dumped state region")

    path = os.path.join(golden_dir, "state.bin")
    with open(path, "rb") as fh:
        blob = fh.read()
    if len(blob) % frame_bytes:
        raise SystemExit(f"pixel_suite: {path} is {len(blob)} bytes, not a multiple of "
                         f"{frame_bytes} -- the dumped state regions have changed")
    return blob[off::frame_bytes]


def game_responded(golden_dir):
    """Did the golden take the coin, and did the game then start?

    Without this, a tape that never reaches the machine leaves both sides in attract, every frame
    matches, and the gate PASSes over a run that played nothing. The input latch alone is not
    enough -- rewritten from the port every NMI, it proves the bits arrived, not that the machine
    acted. The two state cells prove the response.
    """
    latch = state_column(golden_dir, INPUT_LATCH)
    return {
        "coin bits delivered": [f for f, v in enumerate(latch) if v & 0x01],
        "start bits delivered": [f for f, v in enumerate(latch) if v & 0x08],
        "coin accepted": [f for f, v in enumerate(state_column(golden_dir, COIN_TAKEN)) if v],
        "play active": [f for f, v in enumerate(state_column(golden_dir, PLAY_ACTIVE)) if v],
    }


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--rompath", default=os.path.join(GAME, "rom"))
    p.add_argument("--frames", type=int, default=GOLDEN_FRAMES - 1)
    p.add_argument("--work", default=os.path.join(GAME, "out", "pixelwork"))
    p.add_argument("--layer", choices=("idiomatic", "oracle"), default=None,
                   help="which layer to render vs MAME. Default reads manifest.runtime; the pixel "
                        "gate passes this explicitly, chosen from which layer's files changed.")
    a = p.parse_args()

    try:
        verified = subprocess.run(["mame", "-rompath", a.rompath, "-verifyroms", DRIVER],
                                  capture_output=True, text=True).returncode == 0
    except FileNotFoundError:
        print("pixel_suite: SKIP -- no `mame` on PATH")
        return 0
    if not verified:
        print(f"pixel_suite: SKIP -- romset {DRIVER} not found under {a.rompath}")
        return 0

    os.makedirs(a.work, exist_ok=True)
    go, jo = os.path.join(a.work, "golden"), os.path.join(a.work, "js")
    idiomatic = (a.layer == "idiomatic") if a.layer else (runtime() == "idiomatic")
    offset = GEN_OFFSET if idiomatic else FROZEN_OFFSET
    src = "--layer" if a.layer else "manifest.runtime"
    print(f"  layer: {'IDIOMATIC (generator engine)' if idiomatic else 'oracle (cycle-driven)'}"
          f"; golden offset {offset} (from {src})")
    capture_golden(a.rompath, go, lua_tape(os.path.join(a.work, "tape.lua")))
    render_js(jo, a.frames, idiomatic)

    for label, frames in game_responded(go).items():
        if not frames:
            print(f"pixel_suite: FAIL -- golden shows no '{label}'; this run compares two "
                  "attract screens, which proves nothing.")
            return 1
        print(f"  golden: {label:22} frames {frames[0]}..{frames[-1]}")

    _, _, bpf = pixel_gate.screen_geometry(HW)
    got = os.path.getsize(os.path.join(jo, "frames.rgb")) // bpf
    if got < a.frames - 1:
        print(f"pixel_suite: INCOMPLETE -- render delivered {got} of {a.frames - 1} frames; "
              "a comparison this short concludes nothing.")
        return 1

    d = pixel_gate.frame_diffs(os.path.join(jo, "frames.rgb"),
                               os.path.join(go, "frames.rgb"), HW, offset=offset)
    rc = 0
    coin_js = LUA_COIN + TAPE_OFFSET + FROZEN_OFFSET - offset
    for label, frm in (("boot+attract+play", DIFF_FROM),
                       ("gameplay (coin on)", coin_js)):
        r = pixel_gate.rough_verdict(d, HW, from_frame=frm)
        print(f"  {label:20} frames={r['frames']:5d} differ={r['frames_differing']:5d} "
              f"max={r['max_pixels']:5d}px ({r['max_pct']:6.3f}%) "
              f"worst@{r['worst_frame']} -> {r['verdict']}")
        if r["verdict"] != pixel_gate.PASS:
            rc = 1
    bw, bover, bat = band_worst(os.path.join(jo, "frames.rgb"),
                                os.path.join(go, "frames.rgb"), offset, DIFF_FROM)
    bverdict = pixel_gate.PASS if bover == 0 else pixel_gate.FAIL
    print(f"  {'band rows ' + str(BAND_FROM) + '..':20} worst={bw:5d}px (budget {BAND_MAX_PX}) "
          f"over={bover} worst@{bat} -> {bverdict}")
    if bover:
        rc = 1

    print(f"pixel_suite: {'PASS' if rc == 0 else 'FAIL'}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
