#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Time Pilot gameplay pixel gate: JS render vs MAME, through coin -> start -> play.

Attract is the easy half -- it takes no input, so a golden captures itself, and for a long
time that was the only thing this game's pixel path had ever been shown. It reached 7 NMIs.
This drives the same tape into both emulators and compares every frame.

THE TAPE OFFSET IS +1 AND IT IS MEASURED, NOT GUESSED. MAME's frame notifier and the JS
boundary sample count from different origins, so the same tape lands a frame apart. Anchor,
with both tapes pressing at frame 400: the first frame the coin alters RAM is JS 401 and
MAME 402, 13 bytes on both sides. So the JS tape presses ONE FRAME LATER than the lua tape.
Verified discriminating: at +1 the state diff is byte-for-byte over all 1802 frames; at +2
it fails at frame 402. Re-derive this if the tape's timing changes; do not carry it on faith.

Rendering is slow. --frames trades coverage for time; the default covers the golden except
its final frame.
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(GAME))
sys.path.insert(0, os.path.join(REPO, "tools"))

import pixel_gate  # noqa: E402
from hardware import Hardware  # noqa: E402

HW = os.path.join(REPO, "boards", "timeplt", "hardware.json")
DRIVER = "timeplt"
SECONDS = 30
GOLDEN_FRAMES = 1802          # floor(60.0 * 30) + 2, the capture's own length

LUA_COIN, LUA_START = 400, 500
TAPE_OFFSET = 1               # measured; see the module docstring
HOLD = 8

# Every frame is compared. The Pit's gate starts at frame 2, so the natural assumption is
# that this one must skip a boot transient too -- it does not. Measured over the whole run:
# frame 0 differs by ZERO pixels, and the only differing frames are well inside tolerance.
DIFF_FROM = 0

# What the golden must show before its pixels mean anything. Each reads 0x00 for the whole of
# two undriven captures (30s and 60s), so any of them moving is caused by the tape.
#
# Pick anchors that are zero in attract FOR A REASON. An earlier choice here, 0xA9D3, is the
# first byte of a four-byte record copied from a ROM table; it reads zero in attract only because
# attract selects the one row whose first byte happens to be zero. On an easier difficulty a
# perfectly good coined run loads a different row and the check FAILS a passing game.
INPUT_LATCH = 0xA9AE   # raw IN0 mirror, rewritten every NMI: 0x01 coin held, 0x08 start held
COIN_TAKEN = 0xA981    # 0 -> non-zero when the machine ACCEPTS the coin (debounced rising edge)
PLAY_ACTIVE = 0xAD30   # explicit flag: stored 0xFF when play begins, cleared with xor a


def lua_tape(path):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"""-- Generated by pixel_suite.py -- coin then 1P start on IN0.
local IN0 = manager.machine.ioport.ports[":IN0"]
assert(IN0, "no :IN0")
local coin, start = IN0.fields["Coin 1"], IN0.fields["1 Player Start"]
assert(coin and start, "missing Coin 1 / 1 Player Start")
local f = 0
_G.__pt = emu.add_machine_frame_notifier(function()
  f = f + 1
  coin:set_value((f >= {LUA_COIN} and f < {LUA_COIN + HOLD}) and 1 or 0)
  start:set_value((f >= {LUA_START} and f < {LUA_START + HOLD}) and 1 or 0)
end)
""")
    return path


def capture_golden(rompath, out, tape):
    subprocess.run(
        [sys.executable, os.path.join(REPO, "tools", "mame_golden.py"),
         "--hardware", HW, "--lua-dir", os.path.join(HERE, "lua"),
         "--rompath", rompath, "--out", out, "--seconds", str(SECONDS),
         "--tape", tape],
        check=True)


def render_js(out, frames):
    subprocess.run(
        ["node", os.path.join(HERE, "render.js"), "--frames", str(frames),
         "--input", f"0xc300=0x01@{LUA_COIN + TAPE_OFFSET}:hold{HOLD}",
         "--input", f"0xc300=0x08@{LUA_START + TAPE_OFFSET}:hold{HOLD}",
         "--frames-out", out],
        check=True)


def state_column(golden_dir, addr):
    """Every frame's value of one work-RAM cell, read out of the golden's state dump.

    Geometry comes from the same hardware.json the capture used, which already checks its
    regions sum to the declared frame size -- so a layout change cannot silently mis-index.
    """
    regions = Hardware.load(HW).state_regions
    frame_bytes = sum(size for _n, _b, size in regions)
    off = 0
    for _name, base, size in regions:
        if base <= addr < base + size:
            off += addr - base
            break
        off += size
    else:
        raise SystemExit(f"pixel_suite: 0x{addr:04X} is not in any dumped state region")

    path = os.path.join(golden_dir, "state.bin")
    with open(path, "rb") as fh:
        blob = fh.read()
    if len(blob) % frame_bytes:
        raise SystemExit(f"pixel_suite: {path} is {len(blob)} bytes, not a multiple of "
                         f"{frame_bytes} -- the dumped state regions have changed")
    return blob[off::frame_bytes]


def game_responded(golden_dir):
    """Report whether the golden took the coin, and whether the game then started.

    Without this the suite has a silent hole: if the tape fails to reach the machine, the
    golden stays in attract, the JS side stays in attract with it, every frame matches, and
    the gate reports PASS over a run that played nothing. Checking the input latch alone is
    not enough -- it is rewritten from the port every NMI, so it proves the bits arrived,
    not that the machine acted on them. The two state cells prove the response.
    """
    latch = state_column(golden_dir, INPUT_LATCH)
    return {
        "coin bits delivered": [f for f, v in enumerate(latch) if v & 0x01],
        "start bits delivered": [f for f, v in enumerate(latch) if v & 0x08],
        "coin accepted": [f for f, v in enumerate(state_column(golden_dir, COIN_TAKEN)) if v],
        "play active": [f for f, v in enumerate(state_column(golden_dir, PLAY_ACTIVE)) if v],
    }


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--rompath", default=os.path.join(GAME, "rom"))
    p.add_argument("--frames", type=int, default=GOLDEN_FRAMES - 1)
    p.add_argument("--work", default=os.path.join(GAME, "out", "pixelwork"))
    a = p.parse_args()

    # Both BYO-ROM absences skip the same way: no romset and no MAME are the same situation
    # to a fresh clone, and neither is a failure of this game's translation.
    try:
        verified = subprocess.run(["mame", "-rompath", a.rompath, "-verifyroms", DRIVER],
                                  capture_output=True, text=True).returncode == 0
    except FileNotFoundError:
        print("pixel_suite: SKIP -- no `mame` on PATH")
        return 0
    if not verified:
        print(f"pixel_suite: SKIP -- romset {DRIVER} not found under {a.rompath}")
        return 0

    os.makedirs(a.work, exist_ok=True)
    go, jo = os.path.join(a.work, "golden"), os.path.join(a.work, "js")
    capture_golden(a.rompath, go, lua_tape(os.path.join(a.work, "tape.lua")))
    render_js(jo, a.frames)

    # THE GAME MUST HAVE RESPONDED. Checked before the pixels, for the reason in
    # game_responded(). Reported in order so a failure says which stage broke.
    for label, frames in game_responded(go).items():
        if not frames:
            print(f"pixel_suite: FAIL -- golden shows no '{label}'; this run compares two "
                  "attract screens, which proves nothing.")
            return 1
        print(f"  golden: {label:22} frames {frames[0]}..{frames[-1]}")

    # COMPLETENESS. A render that delivered fewer frames than asked still compares clean
    # over the frames it did deliver, so checking the diff alone reports a truncated run as
    # a pass. runFrames publishes one image per boundary, so want-1 is the attainable max.
    _, _, bpf = pixel_gate.screen_geometry(HW)
    got = os.path.getsize(os.path.join(jo, "frames.rgb")) // bpf
    if got < a.frames - 1:
        print(f"pixel_suite: INCOMPLETE -- render delivered {got} of {a.frames - 1} frames; "
              "a comparison this short concludes nothing.")
        return 1

    d = pixel_gate.frame_diffs(os.path.join(jo, "frames.rgb"),
                               os.path.join(go, "frames.rgb"), HW)
    rc = 0
    for label, frm in (("boot+attract+play", DIFF_FROM),
                       ("gameplay (coin on)", LUA_COIN + TAPE_OFFSET)):
        r = pixel_gate.rough_verdict(d, HW, from_frame=frm)
        print(f"  {label:20} frames={r['frames']:5d} differ={r['frames_differing']:5d} "
              f"max={r['max_pixels']:5d}px ({r['max_pct']:6.3f}%) "
              f"worst@{r['worst_frame']} -> {r['verdict']}")
        if r["verdict"] != pixel_gate.PASS:
            rc = 1
    print(f"pixel_suite: {'PASS' if rc == 0 else 'FAIL'}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
