// SPDX-License-Identifier: GPL-3.0-only

/**
 * Galaxian idiomatic-layer registry + the work-RAM/hardware names its decompiled routines read.
 *
 * resolveAllIdiomatic() reads ROUTINES: each 0xADDR maps to ./idiomatic/<name>.js exporting <name>,
 * wired OVER the translated oracle; a routine with no entry falls back to its frozen oracle.
 * This is §4 decompile batch 1 (leaves): routines keep loc_<addr> names — the understand pass renames.
 * Tag: [code] understood from the routines that touch the cell; grounding ([seen]) is a later pass.
 * Cells whose role two derivers read differently stay loc_<addr> placeholders (names-debt.txt).
 */

// Return-stack scratch window (measured §3; excluded from grounding write-attribution).
export const STACK_SCRATCH = { lo: 0x43e0, hi: 0x4400 };

// Hardware ports / discrete-sound latches (board-mapped).
export const IN0 = 0x6000; // [code] IN0 input port (read)
export const COIN_LOCKOUT = 0x6002; // [code] coin-lockout latch (D0 = coin_lock output)
export const COIN_COUNTER_0_LATCH = 0x6003; // [code] coin-counter 0 hardware output
export const SOUND_LFO_FREQ = 0x6004; // [code] discrete-sound LFO frequency latch base
export const SOUND_W_REG4 = 0x6804; // [code] discrete-sound write register 4
export const SOUND_W_REG5 = 0x6805; // [code] discrete-sound write register 5

// Tilemap VRAM.
export const VRAM_BASE = 0x5000; // [code] tilemap VRAM base
export const PLAYER2_STATUS_VRAM = 0x50e0; // [code] player-2 status tilemap cell
export const PLAYER1_STATUS_VRAM = 0x5340; // [code] player-1 status tilemap cell

// Work RAM.
export const RNG_SEED = 0x401e; // [code] 8-bit LCG PRNG seed
export const GAME_STATE = 0x4005; // [code] game state index (cleared by the fill re-seed)
export const SEQUENCE_STATE = 0x400a; // [code] top-level sequence state-machine step index
export const VRAM_WRITE_PTR = 0x400b; // [code] 16-bit VRAM fill write cursor
export const CURRENT_PLAYER = 0x400d; // [code] active player index (0/1)
export const PLAYER1_SCORE_BCD = 0x40a2; // [code] player-1 packed-BCD score (3 bytes)
export const PLAYER2_SCORE_BCD = 0x40a5; // [code] player-2 packed-BCD score (3 bytes)
export const MESSAGE_SCROLL_ENABLE = 0x40b0; // [code] message-scroller enable/countdown flag
export const SOUND_SEQ_ACTIVE = 0x41cd; // [code] sound-sequence active flag
export const SOUND_TONE_DURATION = 0x41ce; // [code] sound tone duration
export const SOUND_PITCH = 0x41c1; // [code] staged sound pitch value (fed to 0x7800)
export const SOUND_SEQ_PTR = 0x41d3; // [code] sound-sequence 16-bit pointer
export const OBJ_SWEEP_DIRECTION = 0x420d; // [code] object sweep direction flag (0=ascending, 1=descending)
export const SOUND_LFO_LEVEL = 0x421f; // [code] sound LFO level shadow

// loc_<addr> placeholders — role not yet consensus-confident; allowlisted in names-debt.txt, named at grounding.
export const loc_1e68 = 0x1e68;
export const loc_1edf = 0x1edf;
export const loc_4001 = 0x4001;
export const loc_4002 = 0x4002;
export const loc_4007 = 0x4007;
export const loc_4008 = 0x4008;
export const loc_4009 = 0x4009;
export const loc_401a = 0x401a;
export const loc_4021 = 0x4021;
export const loc_4028 = 0x4028;
export const loc_4195 = 0x4195;
export const loc_41b5 = 0x41b5;
export const loc_41c0 = 0x41c0;
export const loc_41cf = 0x41cf;
export const loc_41d1 = 0x41d1;
export const loc_41d2 = 0x41d2;
export const loc_41d6 = 0x41d6;
export const loc_41df = 0x41df;
export const loc_4208 = 0x4208;
export const loc_420b = 0x420b;

// batch 2 -- descriptive cells ([code], grounding pending)
export const SOUND_TONE_TABLE = 0x17a9; // [code] batch 2
export const SOUND_DURATION_TABLE = 0x17c8; // [code] batch 2
export const OBJ_STEP_TABLE = 0x1a45; // [code] batch 2
export const STRIDED_TABLE_SRC = 0x1d71; // [code] batch 2
export const PATH_STEP_TABLE = 0x1e00; // [code] batch 2
export const MESSAGE_PTR_TABLE = 0x235c; // [code] batch 2
export const IN0_SHADOW = 0x4010; // [code] batch 2
export const IN1_SHADOW = 0x4011; // [code] batch 2
export const OBJ_STAGE_BLOCK = 0x4054; // [code] batch 2
export const MESSAGE_CURSOR_PTR = 0x40b1; // [code] batch 2
export const MESSAGE_TEXT_PTR = 0x40b3; // [code] batch 2
export const MESSAGE_DEST_PTR = 0x40b5; // [code] batch 2
export const FLAG_BITS_BASE = 0x4100; // [code] batch 2
export const OCCUPANCY_GRID = 0x4123; // [code] batch 2
export const ROW_OCCUPANCY = 0x41e8; // [code] batch 2
export const COLUMN_OCCUPANCY = 0x41f0; // [code] batch 2
export const OBJ_ACTIVE_FLAG = 0x4200; // [code] batch 2
export const HIT_EVENT_FLAG = 0x4204; // [code] batch 2
export const FORMATION_X_BOUNDS = 0x4210; // [code] batch 2
export const DELAYED_EVENT_REQUEST = 0x4229; // [code] batch 2
export const DELAYED_EVENT_ARMED = 0x422e; // [code] batch 2
export const DELAYED_EVENT_TIMER = 0x422f; // [code] batch 2
export const OBJ_MOVE_CMD = 0x423f; // [code] batch 2
export const OBJ_TABLE = 0x42d0; // [code] batch 2
export const DESCRIPTOR_SLOT_TABLE = 0x4330; // [code] batch 2
export const START_LAMP_0 = 0x6000; // [code] batch 2
export const START_LAMP_1 = 0x6001; // [code] batch 2
export const SOUND_W_REG0 = 0x6800; // [code] batch 2
export const SOUND_W_REG1 = 0x6801; // [code] batch 2
export const SOUND_W_REG2 = 0x6802; // [code] batch 2
export const IRQ_ENABLE = 0x7001; // [code] batch 2
export const STARS_ENABLE = 0x7004; // [code] batch 2
export const SOUND_PITCH_W = 0x7800; // [code] batch 2
// batch 2 -- loc_ placeholders (role not yet consensus-confident)
export const loc_4006 = 0x4006;
export const loc_4013 = 0x4013;
export const loc_4014 = 0x4014;
export const loc_4018 = 0x4018;
export const loc_4020 = 0x4020;
export const loc_4081 = 0x4081;
export const loc_40a0 = 0x40a0;
export const loc_40ab = 0x40ab;
export const loc_4177 = 0x4177;
export const loc_41c2 = 0x41c2;
export const loc_41cc = 0x41cc;
export const loc_41d5 = 0x41d5;
export const loc_41ef = 0x41ef;
export const loc_4201 = 0x4201;
export const loc_4202 = 0x4202;
export const loc_4209 = 0x4209;
export const loc_420a = 0x420a;
export const loc_420e = 0x420e;
export const loc_4213 = 0x4213;
export const loc_4218 = 0x4218;
export const loc_4219 = 0x4219;
export const loc_421a = 0x421a;
export const loc_421b = 0x421b;
export const loc_4220 = 0x4220;
export const loc_4221 = 0x4221;
export const loc_4222 = 0x4222;
export const loc_4224 = 0x4224;
export const loc_4225 = 0x4225;
export const loc_4226 = 0x4226;
export const loc_422b = 0x422b;
export const loc_422c = 0x422c;
export const loc_422d = 0x422d;
export const loc_4245 = 0x4245;
export const loc_4246 = 0x4246;
export const loc_424a = 0x424a;
export const loc_425f = 0x425f;
export const loc_4260 = 0x4260;
export const loc_42b1 = 0x42b1;
export const loc_5193 = 0x5193;
export const loc_51da = 0x51da;

// batch 3 -- descriptive cells ([code], grounding pending)
export const ACTIVE_NEIGHBOR_COUNT = 0x422a; // [code] count of active neighbouring object slots
export const DRAWN_COLUMN_COUNT = 0x4241; // [code] running count of tile-columns queued to redraw
export const PACKED_FLAG_BITMAP = 0x4180; // [code] 16-byte packed bitmap (bit-per-flag) destination
export const SAVED_STATE_SNAPSHOT = 0x41a0; // [code] base of a 32-byte saved-state block
export const SPRITE_SHADOW_BASE = 0x4060; // [code] base of the sprite staging/shadow area (4-byte records)
export const SPRITE_SOURCE_OBJ_BASE = 0x42b0; // [code] base of 8 object records read as sprite sources (32-byte stride)
export const SUBCOUNTER_REFILL_FLAG = 0x4228; // [code] one-shot flag set when a sub-counter refilled this pass
export const SUBCOUNTER_RELOAD_TABLE = 0x15e3; // [code] reload-value table indexed by sub-counter offset
export const TILE_COLUMN_TABLE = 0x039a; // [code] base of 3-byte source rows for the tile-column draw
export const TILE_COLUMN_TABLE_CONT = 0x03a6; // [code] continuation of the tile-column source-row table
// batch 3 -- loc_ placeholders (role not yet consensus-confident; first two demoted from low-confidence proposals)
export const loc_4000 = 0x4000;
export const loc_4215 = 0x4215;
export const loc_051b = 0x051b;
export const loc_0640 = 0x0640;
export const loc_1ebd = 0x1ebd;
export const loc_400e = 0x400e;
export const loc_4019 = 0x4019;
export const loc_409d = 0x409d;
export const loc_409f = 0x409f;
export const loc_41c4 = 0x41c4;
export const loc_41c8 = 0x41c8;
export const loc_41c9 = 0x41c9;
export const loc_41ca = 0x41ca;
export const loc_421d = 0x421d;
export const loc_421e = 0x421e;
export const loc_51fc = 0x51fc;

// batch 4 -- descriptive cells ([code], grounding pending)
export const DIGIT_FIELD_ALT = 0x5121; // [code] alt-player score-digit VRAM field base
export const DIGIT_FIELD_PRIMARY = 0x5381; // [code] primary-player score-digit VRAM field base
export const FLIP_SCREEN_X = 0x7006; // [code] screen-flip X latch
export const FLIP_SCREEN_Y = 0x7007; // [code] screen-flip Y latch
export const IN2_PORT = 0x7000; // [code] IN2 input port (read)
export const IN2_SHADOW = 0x4012; // [code] IN2 input shadow
export const OBJ_SHADOW_RESEED_TEMPLATE = 0x1db1; // [code] ROM template for the object-shadow reseed
export const SOUND_LFO_RESET_REQUEST = 0x41d0; // [code] sound LFO reset-request flag
export const SOUND_W_REG3 = 0x6803; // [code] discrete-sound write register 3
export const SPAWN_RECORD_TABLE = 0x1dd1; // [code] ROM spawn-record table
export const TEXT_DESCRIPTOR_TABLE = 0x1cf6; // [code] ROM text-descriptor table
export const TILE_BLOCK_TABLE = 0x215b; // [code] ROM tile-block source table
// batch 4 -- loc_ placeholders (role not yet consensus-confident; ROM-addr ones are handler/data pointers)
export const loc_0152 = 0x0152;
export const loc_0503 = 0x0503;
export const loc_0603 = 0x0603;
export const loc_0604 = 0x0604;
export const loc_0682 = 0x0682;
export const loc_0700 = 0x0700;
export const loc_0703 = 0x0703;
export const loc_0830 = 0x0830;
export const loc_1d91 = 0x1d91;
export const loc_400f = 0x400f;
export const loc_401f = 0x401f;
export const loc_4058 = 0x4058;
export const loc_405a = 0x405a;
export const loc_40ac = 0x40ac;
export const loc_4178 = 0x4178;
export const loc_41c7 = 0x41c7;
export const loc_4205 = 0x4205;
export const loc_4206 = 0x4206;
export const loc_4223 = 0x4223;
export const loc_4238 = 0x4238;
export const loc_42b2 = 0x42b2;
export const loc_42b3 = 0x42b3;
export const loc_4391 = 0x4391;
export const loc_51dc = 0x51dc;
export const loc_521a = 0x521a;
export const loc_521c = 0x521c;
export const loc_5241 = 0x5241;
export const loc_5300 = 0x5300;
export const loc_5320 = 0x5320;

// batch 5 -- descriptive cells ([code], grounding pending)
export const IN1 = 0x6800; // [code] IN1 input port (read; write side is SOUND_W_REG0)
export const HIGH_SCORE_BCD = 0x40a8; // [code] high-score packed-BCD score (3 bytes)
export const MARKER_ROW_VRAM = 0x539e; // [code] marker-row VRAM base (5-slot marker row)
// batch 5 -- loc_ placeholders (role not yet consensus-confident)
export const loc_4004 = 0x4004;
export const loc_4015 = 0x4015;
export const loc_4016 = 0x4016;

// batch 6 -- descriptive cells ([code], grounding pending)
export const PRIMARY_TRIGGER_BLOCK = 0x4176; // [code] primary spawn trigger-flag block (4 flags, 0x4176..0x4179)
export const SECONDARY_TRIGGER_BLOCK = 0x4165; // [code] secondary spawn trigger-flag block (primary index remapped -17)
// batch 6 -- loc_ placeholders (role not yet consensus-confident)
export const loc_4003 = 0x4003;
export const loc_2157 = 0x2157;
export const loc_40ad = 0x40ad;
export const loc_40ae = 0x40ae;

// spine-unblock batch -- descriptive cells ([code], grounding pending)
export const SOUND_W_REG6 = 0x6806; // [code] discrete-sound write register 6 (sound-driver composite latch)
export const SOUND_W_REG7 = 0x6807; // [code] discrete-sound write register 7 (rotate-right of the composite)

// Idiomatic overrides wired OVER the translated oracle (batch 1, leaves-first). Names stay loc_<addr>
// this pass; role is a [code] reading; cert lifts to "seen" at grounding.
export const ROUTINES = {
  0x003c: { name: "advanceRandomSeed", role: "[seen] advance the 8-bit LCG PRNG seed (RNG_SEED, 0x401e) one step (seed*5+1) and return the new byte as this frame's random draw", cert: "seen" },
  0x0322: { name: "enterSequenceStep1", role: "[code] RST-28 sequence-state handler: set SEQUENCE_STATE (0x400a) to 1 and arm the step-1 dwell cascade (0x4008/0x4009 = 3,3)", cert: "code" },
  0x0331: { name: "tickCascadeCountdown", role: "[seen] shared dec-and-carry timer tick: decrement the byte at HL; on expiry step to the next in-page byte and increment it. Both current callers pass HL=0x4009, carrying into SEQUENCE_STATE (0x400a)", cert: "seen" },
  0x050f: { name: "armStateAdvanceGate", role: "[code] store the armed marker (3) into gate byte 0x41b5, which the state handler stepPlaySubstate6 tests as nonzero to take its advance/proceed path", cert: "code" },
  0x0515: { name: "armSubstateAdvanceGate", role: "[seen] store the armed marker (3) into gate byte 0x4195, tested by the sub-state handler stepAltPlaySubstate6 to take its advance-and-show path", cert: "seen" },
  0x0598: { name: "seedObjectRamShadowField", role: "[seen] copy 32 bytes from a ROM template into one interleaved (stride-2) field of the OBJRAM shadow (0x4021,0x4023,...,0x405f) at screen/formation init", cert: "seen" },
  0x070e: { name: "reloadSequenceDwellTimer", role: "[code] re-arm the mid-tier sequence dwell timer (0x4009) to 0x50 (80 ticks) after the handler sets the next state", cert: "code" },
  0x08e5: { name: "clearGateOnPendingRequest", role: "[code] When request flag 0x420b bit0 is pending, acknowledge it (clear 0x420b) and clear the behavior gate 0x4208 that runGameplayFrameAndAdvanceOnFieldClear/advanceFormationSweepOscillator test.", cert: "code" },
  0x090b: { name: "loc_090b", role: "[code] Shared stack epilogue of the enqueueCommandWord path: pop the caller's saved HL and return; no work-RAM effect.", cert: "code" },
  0x0972: { name: "broadcastToStridedTable", role: "[seen] Broadcast the byte in A across the 9-cell stride-2 work-RAM table at 0x4028 (0x4028,0x402a,...,0x4038).", cert: "seen" },
  0x097d: { name: "setSweepDescending", role: "[seen] Set object sweep-direction flag 0x420d (OBJ_SWEEP_DIRECTION) to 1, switching the oscillator to its decreasing/descending phase; called by advanceFormationSweepOscillator when the swept 0x420e word reaches the upper bound.", cert: "seen" },
  0x0983: { name: "setSweepAscending", role: "[seen] Clear object sweep-direction flag 0x420d (OBJ_SWEEP_DIRECTION) to 0, switching the oscillator to its increasing/ascending phase; called by advanceFormationSweepOscillator when the swept 0x420e word reaches the lower bound.", cert: "seen" },
  0x0df6: { name: "commitMoveToTargetX", role: "[seen] Commit an object (IX record) to a horizontal move toward a chosen target X: store target X (ix+0x19), the signed per-frame step delta current-minus-target (ix+0x09), zero the move accumulator (ix+0x1a..0x1c), and advance the planner sub-state (ix+0x02).", cert: "seen" },
  0x10d8: { name: "settleObjectXAtRest", role: "[seen] Per-frame settle handler: step the object coordinate ix+0x04 up one count per frame until it lands within 5 of the rest value 0xc8 (200), then hold.", cert: "seen" },
  0x10f0: { name: "armObjectAnimAndRequestSound", role: "[code] Sub-state-0 entry of a deactivated object's animation: seed the animation timers, advance its sub-state, and post a position-keyed sound request", cert: "code" },
  0x113d: { name: "endObjectAnimOnTimerExpiry", role: "[code] Sub-state-2 tick of the deactivated-object animation: count the dwell timer down and clear the object's state flag when it expires", cert: "code" },
  0x1146: { name: "noopAnimDispatchSlot", role: "[code] No-op terminal slot (sub-state 3) of the object-animation dispatch table", cert: "code" },
  0x1292: { name: "bumpCountIfNeighborsInactive", role: "[code] Return the count incremented by one only when both look-ahead object slots are inactive, else unchanged", cert: "code" },
  0x15df: { name: "reloadExpiredCounterAndTally", role: "[seen] Reload one expired counter cell from its ROM table and return the refill tally incremented", cert: "seen" },
  0x16a6: { name: "driveDecayingSoundSweep", role: "[code] On alternate frames, emit the sweep countdown (rotated right two) to the discrete-sound register and tick it down, fading to silence", cert: "code" },
  0x1733: { name: "driveGatedSquareTone", role: "[code] Per-frame tick of a gated square-wave tone: run the duration counter down driving the toggled bit to the sound register, silence when spent", cert: "code" },
  0x1747: { name: "armSoundSequenceOnRequest", role: "[seen] Arm the gated sound sequence on an outstanding request: clear the request gate, raise the active flags, and publish the sequence-data pointer (SOUND_SEQ_PTR).", cert: "seen" },
  0x1815: { name: "stageSoundPitch", role: "[seen] Stage a pitch byte into SOUND_PITCH, the shadow the per-frame sound driver latches to the pitch port.", cert: "seen" },
  0x183a: { name: "armSoundSequenceForSelector16", role: "[code] Dispatch arm for sound-request selector 0x16: clear its sub-flag, raise SOUND_SEQ_ACTIVE and companion, and publish sequence pointer 0x1edf.", cert: "code" },
  0x186c: { name: "stagePitchAndRaiseSoundFlag", role: "[code] Stage pitch (A-1) into SOUND_PITCH and raise the 0x41c0 composite sound flag the driver latches to the sound registers.", cert: "code" },
  0x1886: { name: "advanceSoundPitchRamp", role: "[seen] Advance a rising sound-pitch ramp one step over a {countdown,pitch} pair: tick the countdown, add a fixed step to the pitch, publish it to SOUND_PITCH, and clear the 0x41c0 composite flag; idle when the countdown is drained.", cert: "seen" },
  0x18b2: { name: "broadcastSoundLfoLevel", role: "[seen] Save a sound LFO level to SOUND_LFO_LEVEL, then fan it (rotated right one bit per write) across the four SOUND_LFO_FREQ hardware latches.", cert: "seen" },
  0x18e8: { name: "endMessageScrollOnExpiry", role: "[seen] Tick a countdown at (HL) and, on the zero-crossing, clear MESSAGE_SCROLL_ENABLE (0x40b0) to stop the scroller.", cert: "seen" },
  0x1917: { name: "presetCreditCount", role: "[code] mode-3 branch of coin service serviceCoinInputs: preset the credit count to 9 and clear the coin-phase flag", cert: "code" },
  0x1961: { name: "clampCreditsToMax", role: "[code] overshoot arm of the credit clamp: pin the credit counter back to its 99 ceiling", cert: "code" },
  0x1971: { name: "setCoinPhaseFlag", role: "[code] set arm of the coin-phase toggle: raise the coins-per-credit flag when the first coin of a pair is received", cert: "code" },
  0x1974: { name: "pulseCoinCounter", role: "[seen] drive the coin-counter output pulse and tick down its pulse-width timer", cert: "seen" },
  0x1989: { name: "clearCoinLockout", role: "[code] release the coin mechanism by clearing the coin-lockout latch", cert: "code" },
  0x1ceb: { name: "drawTextColumn", role: "[code] draw a run of characters down a VRAM column, mapping each source byte to a font tile (byte - 0x30)", cert: "code" },
  0x1d58: { name: "resetScreenFillState", role: "[seen] input-gated reset of the screen-fill state: rewind the VRAM write cursor to base, re-arm the full-page fill length, and clear the dispatch flag and game state", cert: "seen" },
  0x210a: { name: "markValueOutOfRange", role: "[code] Clamp's out-of-range arm: forces the fold index B to the fixed 0x80 sentinel when the input is beyond range.", cert: "code" },
  0x214e: { name: "selectPlayerStatusVram", role: "[code] Selects a player's status-column VRAM base (player 1 -> 0x5340, else player 2 -> 0x50e0), returned in HL.", cert: "code" },
  0x2279: { name: "drawBcdDigit", role: "[code] Paints one BCD digit as a font tile (digit+0x90) with leading-zero blanking, then advances the cursor.", cert: "code" },
  0x2290: { name: "selectCurrentPlayerScore", role: "[code] Selects the current player's 3-byte packed-BCD score field (player 1 -> 0x40a2, else player 2 -> 0x40a5), returned in DE.", cert: "code" },
  0x25a0: { name: "stampTilePair", role: "[code] Stamps a pair of consecutive tile codes into two adjacent cells ((HL)=A, (HL+1)=A+1), then steps HL by the stride and the tile code by two.", cert: "code" },
  0x25a9: { name: "drawDoubleHeightTile", role: "[code] Stamps the two halves of a double-height glyph: tile A at (HL) and tile+2 at (HL+0x20), one tilemap row apart; preserves DE.", cert: "code" },
  0x01c6: { name: "primeVramFillAndAdvanceStep", role: "[seen] Attract sequence-step setup: clears the 0x4100 flag-bits block (via rst-0x10) plus status bytes 0x425f/0x4224, seeds VRAM_WRITE_PTR (0x400b)=VRAM_BASE+2, arms the 0x4009 dwell tier to 32, and increments SEQUENCE_STATE (0x400a).", cert: "seen" },
  0x032e: { name: "tickSequenceDwellTimer", role: "[code] Sequence state handler: point HL at the 0x4009 dwell tier and tick the shared cascade countdown (tickCascadeCountdown, 0x0331) each frame, advancing SEQUENCE_STATE (0x400a) on the tier's expiry.", cert: "code" },
  0x0336: { name: "tickPrescaledSequenceTimer", role: "[seen] Prescaled sequence-dwell state: decrement sub-timer 0x4008 each frame; on wrap reload it to 0x3c and tick the 0x4009 dwell tier via tickCascadeCountdown (0x0331), advancing SEQUENCE_STATE on that tier's expiry.", cert: "seen" },
  0x0341: { name: "activateDescriptorSlot", role: "[seen] Activate one 32-byte descriptor slot at DESCRIPTOR_SLOT_TABLE (0x4330) + (number-1)*32: stamp [0]=1 (active), [1]=0, [2]=0x0d, [4]=0, [5]=0x0c, [7]=slot index; leaves [3]/[6] untouched.", cert: "seen" },
  0x0363: { name: "clearStridedTable", role: "[seen] Per-state reset: broadcast 0 across the 9-cell stride-2 work-RAM table at 0x4028 (0x4028,0x402a,...,0x4038) via broadcastToStridedTable (0x0972).", cert: "seen" },
  0x03af: { name: "drawTileColumnTriple", role: "[code] Render primitive: copy 3 source bytes up a VRAM tilemap column (dst low byte -0x20 per row within the fixed page), then advance +0x62 to line up the next column; returns advanced src (HL) and dst (DE/A) for chained column draws.", cert: "code" },
  0x03c0: { name: "blankTileColumns", role: "[code] Render primitive: blank a run of B tilemap columns starting at 0x5193, stamping BLANK_TILE (0x10) into 3 cells per column (HL -0x20 per row, 16-bit, borrows into the high byte), advancing +0x62 per column (djnz, 0->256).", cert: "code" },
  0x03d7: { name: "advanceGameStateOnCredit", role: "[code] RST continuation (pushed by loc_0156 as the post-dispatch return): when credit count 0x4002 != 0, advance GAME_STATE (0x4005) and reset the attract sub-state cluster — clear 0x4007, SEQUENCE_STATE (0x400a), 0x41c2, sound-sweep 0x41df, and MESSAGE_SCROLL_ENABLE (0x40b0); zero credits = no-op", cert: "code" },
  0x0473: { name: "driveStartButtonLamps", role: "[code] RST-28 state idx 3: drive the two start-button lamp latches (0x6000/0x6001) from the credit/start count 0x4002, gated on 0x425f bit5 — bit5 clear clears both lamps; else 0 credits leaves them, 1 credit lights lamp0, >=2 lights both", cert: "code" },
  0x0550: { name: "initPlayfieldState", role: "[code] play-state sub-state-0 init (dispatched by loc_0536 state 3 and loc_077b state 4): clear both start lamps, zero-fill work-RAM spans (0x4100-0x417f, 0x4200-0x422f, 0x4260-0x42a5), set 0x425f=0 and 0x4226=1, advance SEQUENCE_STATE (0x400a), arm dwell 0x4009=0x20, and point the VRAM fill cursor 0x400b at 0x5000", cert: "code" },
  0x0595: { name: "seedObjectShadowFromRom", role: "[seen] seed the interleaved (stride-2) OBJRAM-shadow field 0x4021,0x4023,...,0x405f from ROM template 0x1d71 at screen/formation init — sets HL=0x1d71 and delegates to seedObjectRamShadowField", cert: "seen" },
  0x0646: { name: "unpackBitmaskToFlagBytes", role: "[seen] unpack a 16-byte packed bitmask at (DE) into 128 one-byte-per-bit flags at FLAG_BITS_BASE (0x4100), LSB-first — write 1 for a set bit, 0 for a clear one; returns DE advanced past the 16 mask bytes", cert: "seen" },
  0x070d: { name: "advanceSubstateAndReloadDwell", role: "[code] advance the sub-state counter at (HL) (both callers pass HL=SEQUENCE_STATE 0x400a) then re-arm the mid-tier dwell timer via reloadSequenceDwellTimer (0x070e -> 0x4009=0x50)", cert: "code" },
  0x0764: { name: "packFlagBytesToBitmask", role: "[code] pack bit0 of the 128 flag bytes at FLAG_BITS_BASE (0x4100), LSB-first, into a 16-byte bitmap at (DE); returns DE advanced +16 for a chained block copy (exact inverse of unpackBitmaskToFlagBytes)", cert: "code" },
  0x0837: { name: "moveControlledObjectAndStageSprite", role: "[code] When active, step the input/AI-controlled object one unit along its axis (clamped to [23,233]); when inactive, park position at 0 or stage current position under the alternate code; then stage the negated position + code as four (value,code) pairs into OBJ_STAGE_BLOCK.", cert: "code" },
  0x08bc: { name: "advancePlayerShot", role: "[code] Drive the single player shot: while the gate (0x4208 bit0) is armed, drain the position counter (0x4209) by 4/frame and raise the retire flag (0x420b) as it lands in the near-end window [14,17]; when idle, reset the counter to 220 (parked at the bottom) and seed the field (0x420a) from the player X (0x4202).", cert: "code" },
  0x0908: { name: "commitQueueWriteHead", role: "[seen] Persist the advanced write-head index (0x40a0) back to the command/event queue after an enqueue, then return via the shared stack epilogue loc_090b.", cert: "seen" },
  0x096f: { name: "broadcastNegatedSweepToStridedTable", role: "[seen] Compute the two's-complement of the formation-sweep low byte (L) and broadcast it across the strided work-RAM table 0x4028,0x402a,...,0x4038 via broadcastToStridedTable.", cert: "seen" },
  0x098e: { name: "summarizeFormationOccupancy", role: "[seen] Reduce the occupancy grid (0x4123) into per-row OR summaries (ROW_OCCUPANCY 0x41e8, behind 2 guard cells) and per-column OR summaries (COLUMN_OCCUPANCY 0x41f0, behind 3 guards), derive the horizontal sweep bound pair scanned inward from each end into FORMATION_X_BOUNDS (0x4210), and fold four region-clear flags (0x4220/0x4221/0x4225/0x4226) from the row summaries and two object-table columns.", cert: "seen" },
  0x0a32: { name: "armBehaviorGateOnInputOrTimer", role: "[code] When enabled (OBJ_ACTIVE_FLAG 0x4200 bit0 set) and not already armed (0x4208 bit0 clear): on the timer path (0x4006 bit0 clear) arm the gate 0x4208 only when the low 5 bits of 0x425f are zero (~every 32 frames); on the input path (0x4006 bit0 set) test bit4 of the selected input shadow (0x4010/0x4011 via 0x4018) masked by its guard (0x4013/0x4014) and, if active, arm both the gate 0x4208 and companion flag 0x41cc.", cert: "code" },
  0x0a74: { name: "advanceAndRenderProjectiles", role: "[code] Integrate and render the 7 moving-object records at 0x4260 (each two 5-byte sub-slots; a phase bit 0x425f picks the leading sub-slot): advance sub-position (deactivate on overflow), integrate the 16-bit position by 2x the signed velocity, deactivate when it leaves the vertical window, and write each sprite's Y and code into the sprite shadow at 0x4081 (mirrored by direction flag 0x4018, +/-1 code nudge on the first three).", cert: "code" },
  0x0b8d: { name: "flagProjectileHitOnPlayer", role: "[code] Per-entry collision test: for an active enemy-shot entry (bit0 of byte0), box-test entry X vs the player-X reference (loc_4202) and entry Y across a near/far band; on overlap deactivate the entry (byte0=0) and raise HIT_EVENT_FLAG (0x4204)=1.", cert: "code" },
  0x0c20: { name: "renderObjectSprite", role: "[seen] Build one hardware sprite record (Y,attr,sprite#,X) at IY from the object struct at IX: active (byte0 bit0) copies position (X=objX-8, Y=~objY-yOffset) and folds the signed heading (ix+5) into a display attr added to base attr (ix+0f); secondary-active (byte1 bit0) uses fixed sprite#7 + alt attr (ix+12); both clear parks the sprite off-screen (248,248).", cert: "seen" },
  0x0d71: { name: "advanceObjectPathStep", role: "[code] Object-AI state-1 handler: walk the per-object cursor (ix+19) through PATH_STEP_TABLE (0x1e00), add the delta pair to Y (ix+3) then direction-controlled X (ix+4, dir bit ix+6 bit0); if X (plus 7px margin) crosses the near edge force state (ix+2)=5 (fall-away); else advance cursor, tick throttle (ix+16, reload 4) and on expiry nudge cross-step (ix+5) and tick leg counter (ix+17), advancing state when the leg finishes.", cert: "code" },
  0x0f3c: { name: "homeObjectXTowardPlayer", role: "[code] Object-AI state-7 handler: bump frame counter (ix+3); steer the object's 16-bit X:subpixel pair (ix+4 high, ix+9 low) by ~4x the signed distance to the target-X reference loc_4202 (with the rounding bias) each frame; advance state (ix+2) when the dwell timer (ix+16) reaches 0.", cert: "code" },
  0x1060: { name: "advanceObjectPathStepAscending", role: "[code] Ascending/mirrored path-walk arm: add the PATH_STEP_TABLE byte at HL to Y (ix+4) and advance the walk cursor; tick the move throttle (ix+16), and on expiry step the heading (ix+5) and tick the leg counter (ix+17); on leg finish advance the dispatch state (ix+2) and reload throttle=3, leg=12, heading=244, cursor=0.", cert: "code" },
  0x109b: { name: "initObjectPhaseSteps", role: "[seen] Object-AI state-13 entry: derive step count n=(~seed[ix+7])&3; write n+1 to step-count (ix+22) and code byte ((n+1)<<4)+140 to ix+3; arm phase timer (ix+16)=24; advance sub-state (ix+2); clear ready flag (ix+15) then re-arm it (=24) only when n==0.", cert: "seen" },
  0x1112: { name: "tickDeactivatedObjectAnim", role: "[code] Sub-state-1 tick of the deactivated/dying object animation: count the fast timer (ix+16) down, reloading it (=4) and bumping the companion (ix+18) on elapse; then the slow timer (ix+17); on slow elapse either retire the object (state byte ix+1=0) or — when the position field ix+7>=112 — reload fast=50, seed the companion from global loc_422d+32, and advance the sub-state (ix+2).", cert: "code" },
  0x1147: { name: "positionObjectFromGridCell", role: "[code] Unpack an object's packed grid-cell (record+7) into its position fields, matching the grounded render convention (renderObjectSprite): row bits set the X field record+3=124-3/4*row; column bits set the Y field record+4=formation anchor(0x420e)+col*16+7. Display axes are rotated 90deg from the formation grid.", cert: "code" },
  0x116b: { name: "advanceObjectFlightCurve", role: "[code] Run ((record+0x18 seed)&3)+1 steps of a cross-coupled fixed-point rotation over two 16-bit accumulators in the object record (hi/lo at record+0x19/+0x1b and +0x1a/+0x1c), each step adding twice the other accumulator's sign-extended high byte with a high-byte==128 overflow-revert guard; the accumulator high bytes become the swoop/flight offset the dive AI adds to screen Y.", cert: "code" },
  0x14f3: { name: "rampCounterToCeiling", role: "[code] Gated two-tier prescaler (outer 0x4218 reload 60 -> inner 0x4219 reload 20): while OBJ_ACTIVE_FLAG(0x4200) bit0 set and inhibit 0x422b bit0 clear, step the 0..7 counter 0x421a up by one per double-wrap, clamped at 7 (a slow pace/difficulty ramp; advanceStageAndReseedFormation resets 0x421a=0 on a stage advance).", cert: "code" },
  0x1555: { name: "scheduleDelayedEvent", role: "[code] Guarded (OBJ_ACTIVE_FLAG & 0x41ef bit0 set, inhibit 0x422b bit0 clear) two-tier timer that arms the delayed-event triple; mode bit 0x4006 clear -> on outer(0x4245,60)/inner(0x4246,5) cascade elapse arm fixed (DELAYED_EVENT_TIMER 0x422f=90, 0x424a=45, DELAYED_EVENT_ARMED 0x422e=1); mode set -> derive the payload from 0x4221 or the byte-sums of 0x4177/0x421a and fan it via rotations into the triple.", cert: "code" },
  0x15c3: { name: "fireDelayedEventRequest", role: "[code] Delayed one-shot: while DELAYED_EVENT_ARMED (0x422e) bit0 set, count DELAYED_EVENT_TIMER (0x422f) down each frame; on the zero tick disarm (one-shot) and, only if OBJ_ACTIVE_FLAG & 0x41ef bit0 both set, raise DELAYED_EVENT_REQUEST (0x4229).", cert: "code" },
  0x15f4: { name: "selectAttackerRowScan", role: "[code] Seed slot/base from alt flag 0x421b (nonzero -> slot 2/base 157, else slot 1/base 132), scan up to four two-byte slots of ROW_OCCUPANCY (0x41e8) advancing while neither byte of a slot has bit0 set, and store the resulting (slot index, base) pair into 0x4213 for the object-AI row scans (advanceObjectFlightAndFire/advanceHomingObjectFlightAndFire).", cert: "code" },
  0x1621: { name: "armFormationAdvanceTrigger", role: "[code] Gated one-shot: when both status gates 0x4220 and 0x4225 have bit0 set and the pending word 0x4222 is not already armed, write mem16[0x4222]=1 (enable byte=1, countdown 0x4223=0). advanceStageAndReseedFormation later consumes this delayed one-shot to advance the stage/formation selector 0x421b (clamped 0..7), reseed the formation anchor 0x420e=1 and reset the pace counter 0x421a=0.", cert: "code" },
  0x1688: { name: "expireActivityGatedTimer", role: "[code] Gated countdown: while arm flag 0x422b bit0 is set AND an activity gate is open (0x4224!=0 || 0x4221!=0 || 0x4226 bit0), tick counter 0x422c and clear the arm flag 0x422b once it reaches zero -- ends an activity-gated timed phase.", cert: "code" },
  0x16b8: { name: "driveSoundVoicesFromOccupancy", role: "[code] On even frames (0x4007 bit0 clear) sum the 6x10 OCCUPANCY_GRID (0x4123, stride 16) into a tally seeded at 1, light min(tally,3) of the three sound-write latches SOUND_W_REG0..2 (0x6800-2) and zero the rest, then set the near-empty flag 0x4224 (=1 when tally<2, consumed by expireActivityGatedTimer).", cert: "code" },
  0x176c: { name: "advanceSoundSequenceChannel", role: "[code] Advance one sound-sequence channel (descriptor at HL): if active, stage 0x41c0=2 and publish current tone 0x41d5 -> SOUND_PITCH (0x41c1), tick duration 0x41d6; on expiry read next SOUND_SEQ_PTR byte (0xE0 deactivates the channel), else split it into a low-5-bit SOUND_TONE_TABLE index -> 0x41d5 and high-3-bit SOUND_DURATION_TABLE index -> 0x41d6, advancing the cursor.", cert: "code" },
  0x18e7: { name: "endMessageScrollOnExpiryFromDe", role: "[seen] DE-entry adapter to endMessageScrollOnExpiry (0x18e8): restore the countdown pointer from DE (ex de,hl) then tick it and clear MESSAGE_SCROLL_ENABLE (0x40b0) on the zero-crossing to end the message scroll.", cert: "seen" },
  0x1a12: { name: "accumulateObjectPositionWeight", role: "[code] Per-object contribution to accumulator B (register-compute, no memory write): skip unless object (IX) is active (byte0 bit0), Y in one of two 52-row bands from 128, and X delta from reference 0x4202 in the lower half; else fold flag bit7 + delta bits5-6 + band into a 0-15 index and add signed OBJ_STEP_TABLE[idx] (0x1a45) to B.", cert: "code" },
  0x1cb5: { name: "silenceSoundAndDisableIrqStars", role: "[code] Hardware quiesce: set the four SOUND_LFO_FREQ latches (0x6004-7)=1, clear the eight sound registers (0x6800-7), clear IRQ_ENABLE (0x7001) and STARS_ENABLE (0x7004), and drive SOUND_PITCH_W (0x7800)=0xff -- silences audio and halts the vblank interrupt + starfield.", cert: "code" },
  0x20cd: { name: "paintPlayerStatusColumn", role: "[code] Paint a 3-cell VRAM column from HL stepping by DE (top=code+1, middle tile 0x25, bottom tile 0x20) for the player-status indicator; then, only when flags(B) bit4 is clear and gate 0x4006==0, clear status flag 0x40ab.", cert: "code" },
  0x20e1: { name: "mapPackedCoordToVram", role: "[code] Map a packed coordinate byte to a tilemap-VRAM cell address (VRAM_BASE + (high<<8) + low); live-outs HL=cell addr, A=coord bits 6..5, carry=coord bit 4 (callers branch on it).", cert: "code" },
  0x2187: { name: "blankTileBlock4x4", role: "[code] Blank a 4x4 tile block in VRAM at 0x51da, writing BLANK_TILE(0x40) to four rows of four cells (row start stride 32).", cert: "code" },
  0x22f1: { name: "renderMessageColumn", role: "[seen] Message painter indexed by A: bit7 blanks the text column, bit6 records dest/text/cursor pointers + clears the column + arms MESSAGE_SCROLL_ENABLE, else draws each glyph up the column (stride -32) to the 63 terminator.", cert: "seen" },
  0x2569: { name: "byteToPackedBcd", role: "[code] Convert a binary byte to packed BCD -- value mod 100 as two decimal digits, tens in the high nibble and units in the low nibble -- returned in A.", cert: "code" },
  0x2585: { name: "drawTileBlock2x2", role: "[code] Draw a 2x2 tile block at HL from seed tile A via two stampTilePair calls -- top pair (A,A+1) then bottom pair (A+2,A+3) one tilemap row down; preserves DE.", cert: "code" },
  0x258c: { name: "drawBottomTilePairRestoreDe", role: "[code] Shared tail of the 2x2 tile-block writers: stamp the bottom tile pair via stampTilePair, then restore the caller's pushed DE from the stack and return.", cert: "code" },
  0x259e: { name: "drawFixedTilePairHorizontal", role: "[code] Stamp a horizontal tile pair from the fixed glyph code 0x2c (44) via stampTilePair, returning the advanced tile/pointer for the caller's loop.", cert: "code" },
  0x25a7: { name: "drawFixedTilePairVertical", role: "[code] Stamp a vertical (double-height) tile pair from the fixed glyph code 0x2c (44) via drawDoubleHeightTile -- seed at HL and the stepped code one tilemap row below.", cert: "code" },
  0x0010: { name: "fillMemoryBlock", role: "[code] RST-10 memory-fill primitive: store A into `count` bytes from HL, advancing HL (count 0 wraps to a 256-byte fill); leaves HL past the fill and B=0", cert: "code" },
  0x0020: { name: "fetchIndexedTableByte", role: "[code] RST-20 indexed table fetch: HL = HL + A (carry into the high byte), then A = (HL); returns the fetched byte and the advanced pointer", cert: "code" },
  0x00d8: { name: "rearmVblankInterruptAndRestoreRegs", role: "[code] Vblank interrupt epilogue: write IRQ_ENABLE (0x7001)=1 to re-arm the next frame's interrupt, restore the six register pairs saved by the prologue (pop iy/ix/hl/de/bc/af), then ret through the interrupted PC", cert: "code" },
  0x01be: { name: "armStepCountdownAndTickSequenceTimer", role: "[seen] loc_0156 sub-state 1: arm countdown cell 0x4019=1, then tick the prescaled sequence timer (tickPrescaledSequenceTimer). 0x4019 is decremented by holdStartLampsThenAdvanceSequence, which advances SEQUENCE_STATE and clears the 0x4100 flag block on its expiry", cert: "seen" },
  0x02fd: { name: "loadDescriptorAndAdvanceSequence", role: "[code] loc_0156 state 13: unpack a packed descriptor bitmask (ROM 0x051b) into the 0x4100 flag block, copy the following 8-byte template into 0x4218, clear 0x425f, set 0x421d=1, increment SEQUENCE_STATE, stamp 0x400b=0x96, and publish pointer 0x0640 into 0x4245", cert: "code" },
  0x0367: { name: "redrawTileColumnsPeriodically", role: "[code] Periodically redraw a run of VRAM tile-columns gated by DRAWN_COLUMN_COUNT (0x4241) and the frame-counter phase (0x425f & 0x3f): <2 counted returns; the blank phase wipes the columns (blankTileColumns), the draw phase repaints them from TILE_COLUMN_TABLE (drawTileColumnTriple)", cert: "code" },
  0x0593: { name: "advanceSequenceStateAndReseedObjectShadow", role: "[code] Advance the pointer's low byte in-page and increment the byte it now names (both callers arrive HL=0x4009, so inc L -> 0x400a bumps SEQUENCE_STATE), then fall through to seedObjectShadowFromRom to reseed the stride-2 OBJRAM shadow from ROM template 0x1d71", cert: "code" },
  0x0712: { name: "setSequenceStateByModeAndReloadDwell", role: "[code] Set the sequence-state cell (0x400a) to 4 or 14 depending on mode bit 0x4006, then re-arm the sequence dwell timer (delegate 0x070e -> 0x4009).", cert: "code" },
  0x073d: { name: "packFlagsToBitmapAndSwitchPlayerState", role: "[code] State-machine terminal (index 7 of loc_0536's table): on dwell-timer expiry, clear SEQUENCE_STATE/0x4222/0x422b, pack the flag bytes into PACKED_FLAG_BITMAP (0x4180) via 0x0764, copy the 8-byte template (0x4218) after it, set CURRENT_PLAYER (0x400d)=1 and GAME_STATE (0x4005)=4.", cert: "code" },
  0x0818: { name: "saveFlagsToSnapshotAndSwitchPlayerState", role: "[code] Mirror terminal (index 7 of loc_077b's table): on dwell-timer expiry, clear SEQUENCE_STATE, set CURRENT_PLAYER (0x400d)=0 and GAME_STATE (0x4005)=3, pack the flag bytes into SAVED_STATE_SNAPSHOT (0x41a0) via 0x0764, and copy the 8-byte companion block (0x4218) after it.", cert: "code" },
  0x0898: { name: "advancePlayerShotAndStageSprite", role: "[code] Service the player shot (advancePlayerShot 0x08bc), then stage its two sprite render cells: 0x409f = (0x4018 bit0 ? counter-1 : ~counter+252) and 0x409d = ~field, from {0x4209,0x420a}.", cert: "code" },
  0x08f2: { name: "enqueueCommandWord", role: "[seen] Append a 16-bit command word (D:E) to the command queue at write-head 0x40a0 when the head slot is free (bit7 set): store hi byte at the slot, lo byte at slot+1, then advance/commit the head (clamped up to floor 0xc0).", cert: "seen" },
  0x0988: { name: "broadcastNegatedFormationSweepToStridedTable", role: "[code] Load the swept formation word (0x420e) and tail-jump into broadcastNegatedSweepToStridedTable (0x096f), which stores -(low byte) across the strided work-RAM table 0x4028,0x402a,...,0x4038.", cert: "code" },
  0x0b77: { name: "flagProjectileHitsOnPlayer", role: "[code] When projectiles are enabled (OBJ_ACTIVE_FLAG 0x4200 bit0 set), loop all 14 projectile entries (base 0x4260, stride 5) through flagProjectileHitOnPlayer (0x0b8d), which box-tests each vs the player and, on overlap, deactivates the entry and raises HIT_EVENT_FLAG (0x4204).", cert: "code" },
  0x0bbe: { name: "stageObjectsToSpriteShadow", role: "[seen] Per-frame sprite-staging driver: renders 8 consecutive object records (SPRITE_SOURCE_OBJ_BASE 0x42b0, 32-byte stride) into 8 consecutive sprite-shadow records (SPRITE_SHADOW_BASE 0x4060, 4-byte stride) via renderObjectSprite, as a band of 3 then a band of 5 at a Y offset selected by loc_4018 bit0.", cert: "seen" },
  0x0ddd: { name: "commitMoveAcrossPlayerX", role: "[code] Object-AI horizontal target picker: signed-halves the gap between the actor's X (record+4) and the player-X reference loc_4202 ([code]-inferred), biases by 16, and clamps to the band on the far/opposite side (right 144-208 when actor is left of the reference, left 48-112 when at/right), then tail-calls commitMoveToTargetX (0x0df6, [seen]) to commit the crossover move.", cert: "code" },
  0x0e6b: { name: "advanceObjectDiveStep", role: "[code] Object-AI dive state handler (rst-28 dispatch slot 4 @0x0ce6): steps the object's position (record+3) by 1 or 2 on the frame-parity bit loc_425f, window-checks it (bump the state index record+2 when inside [6,9)), else runs advanceObjectFlightCurve and folds its heading hi-byte (record+0x19) plus the per-object increment (record+9) into a new screen Y (record+4), bumping the state instead on a signed-boundary carry.", cert: "code" },
  0x0e99: { name: "reseedFormationObjectState", role: "[code] Object-AI state handler (rst-28 dispatch slot 5 @0x0ce6): re-inits the object (X record+3=8 left edge, heading record+5=0, ticks leg counter record+0x17); when enabled+gated (loc_4200 bit0, loc_4224||loc_4221) rolls a fresh random Y (advanceRandomSeed) into record+4, arms hold timer record+0x10=40, and advances state; on the special grid-cell value (record+7 & 0x70 == 0x70) recounts active neighbors into ACTIVE_NEIGHBOR_COUNT (0x422a) and, once none remain, deactivates the object (record+0=0) and ramps difficulty/phase counter loc_421e toward 2.", cert: "code" },
  0x101f: { name: "advanceObjectPathStepDescending", role: "[code] Object-AI descending path-walk handler (rst-28 dispatch slot 10 @0x0cfa): subtracts the current PATH_STEP_TABLE (0x1e00) X delta from record+3 and advances the walk cursor (record+0x13); unless the direction bit (record+6 bit0) hands the Y half to advanceObjectPathStepAscending, subtracts the Y delta from record+4; ticks the move throttle (record+0x10, reload 4) and leg counter (record+0x11), and on a finished leg advances the state and reloads throttle=3/leg=12/heading=12/cursor=0. The subtract-direction mirror of advanceObjectPathStep.", cert: "code" },
  0x108e: { name: "advanceObjectPathStepAlias", role: "[code] Object-AI dispatch slot 11 (@0x0cfc): a bare trampoline that forwards unchanged to advanceObjectPathStep (0x0d71, the slot-1 path-walk handler); it performs no work and holds no state of its own.", cert: "code" },
  0x13e1: { name: "chooseNextAttackerDirection", role: "[code] Sets the shared attacker launch/curve direction flag loc_4215 (0 or 1): the 16-bit formation anchor loc_420e's sign picks which FORMATION_X_BOUNDS (0x4210) edge to measure the 8-bit gap against; within 28px of that edge the flag is forced away from the edge (0 near the high bound, 1 near the low bound), otherwise a fresh random bit (advanceRandomSeed & 1). Consumed by the spawner launchAttackerFromFormation (seeds a new attacker's direction field record+6) and spawnObjectsOnDelayedEvent (left/right column scan).", cert: "code" },
  0x1515: { name: "paceEnemyLaunchTrigger", role: "[code] Gated prescaler that ticks a master counter (0x424a) and, on expiry, sweeps a difficulty-scaled span of attacker sub-counters, refilling each expired one and raising the spawn-trigger flag SUBCOUNTER_REFILL_FLAG (0x4228) that launchAttackerFromFormation consumes to launch a new attacker.", cert: "code" },
  0x1723: { name: "advanceGatedSquareTone", role: "[code] Per-frame tick of a gated square-wave tone channel: drives the tone toggler while gate counter 0x41cc is armed, and at the expiry step parks 0x41cc=0 and re-arms SOUND_TONE_DURATION (0x41ce) to 8.", cert: "code" },
  0x175d: { name: "advanceAllSoundSequenceChannels", role: "[code] Advances all three sound-sequence channels one step per frame by calling advanceSoundSequenceChannel on descriptors 0x41d2, 0x41cf, and SOUND_SEQ_ACTIVE (0x41cd) in turn.", cert: "code" },
  0x180c: { name: "stagePitchFromSoundCounter", role: "[code] Recomputes a staged sound pitch from counter cell 0x41c4 — on an odd selector applies a +96 bias and rotate-right warble, else passes it through — then stages it via stageSoundPitch into SOUND_PITCH (0x41c1).", cert: "code" },
  0x1819: { name: "armSoundSequenceBySelector", role: "[code] When the sound driver is enabled (0x4006 bit0), reads request selector 0x41df: any value != 6 is handed to armSoundSequenceForSelector16; selector 6 arms this sequence (unless SOUND_SEQ_ACTIVE 0x41cd already set) by raising 0x41cf/0x41d6 and publishing SOUND_SEQ_PTR (0x41d3)=0x1ebd.", cert: "code" },
  0x185e: { name: "pulseSoundToneFromCountdown", role: "[code] High-byte handler of a decrementing sound-envelope word (0x41c7, high byte 0x41c8): idle when the high byte is zero, else stores it decremented and stages a bit2-gated two-level pulse (129/0) via stagePitchAndRaiseSoundFlag.", cert: "code" },
  0x1876: { name: "driveRisingPitchRamp", role: "[code] Pitch-ramp arm tick: while arm counter 0x41c9 stays nonzero it advances the rising pitch ramp one step via advanceSoundPitchRamp; at its reset point it clears 0x41c9 and reloads the {countdown,pitch} pair 0x41ca=32.", cert: "code" },
  0x18a6: { name: "decaySoundLfoLevel", role: "[code] Per-frame LFO decay guard: only on the 0x425f==0xff tick with SOUND_LFO_LEVEL (0x421f) nonzero, decrement the level and fan it across the LFO frequency latches via broadcastSoundLfoLevel (0x18b2).", cert: "code" },
  0x18c0: { name: "advanceMessageScroller", role: "[seen] Message-scroller per-frame step: while MESSAGE_SCROLL_ENABLE (0x40b0) bit0 set, emit one glyph up its VRAM column -- advancing MESSAGE_TEXT_PTR (0x40b3) +1 and MESSAGE_DEST_PTR (0x40b5) up one row (-32) -- then tick the delay counter (which stops the scroller on its zero-crossing).", cert: "seen" },
  0x197c: { name: "updateCoinLockoutFromCredits", role: "[code] Drive the coin-lockout latch from the credit count 0x4002: at >=9 release via clearCoinLockout (0x1989 -> COIN_LOCKOUT 0x6002=0); below 9 engage it (COIN_LOCKOUT=1).", cert: "code" },
  0x198e: { name: "computeControlledObjectMoveCommand", role: "[code] Once per 32-frame phase (0x425f) and while loc_4007 bit0 and OBJ_ACTIVE_FLAG (0x4200) bit0 are set: fold both object tables' position weights (accumulateObjectPositionWeight 0x1a12), add a scaled anchor(0x420e)-vs-reference(0x4202) offset and a random +/-1 nudge, and bucket the result into OBJ_MOVE_CMD (0x423f) = 0/4/8.", cert: "code" },
  0x1cdc: { name: "drawTextColumnFromDescriptor", role: "[code] Unpack a 5-byte text descriptor at the record pointer (source word, dest word, count byte) and paint `count` chars up a VRAM column (stride -32) via drawTextColumn (0x1ceb), each source byte mapped to a font tile.", cert: "code" },
  0x1d51: { name: "restartScreenFillOnDwellExpiry", role: "[seen] Screen-fill outer-dwell tick: entered from the tile-strip fill updater (advanceScreenFillStrip gate-zero path / drawScreenFillStripSecondHalf fall-through, HL=0x4008), bump to the high-tier dwell byte 0x4009 and tick it; if already 0 or on the zero-crossing, restart the fill via resetScreenFillState (0x1d58).", cert: "seen" },
  0x20ac: { name: "repaintPlayerStatusColumn", role: "[code] Repaint the player-status column: select CURRENT_PLAYER's (0x400d) status-column VRAM base via selectPlayerStatusVram (0x214e); B bit4 clear -> paint it (paintPlayerStatusColumn 0x20cd); bit4 set -> blank its three cells (tile 16, stride -32) and, when the paired-player flag loc_400e is set, paint the other player's (player^1) column too.", cert: "code" },
  0x211d: { name: "computeTileVariantFromTimer", role: "[code] Fold register B to a 2-bit tile-variant index = (nibble-swap(per-frame counter loc_425f)+B+C)&3, or saturate to the 0x80 out-of-range sentinel via markValueOutOfRange when B>=112; leaves A/flags unchanged.", cert: "code" },
  0x214a: { name: "drawTileBlock2x2AtDe", role: "[code] DE-entry adapter over drawTileBlock2x2: ex de,hl so the pointer arriving in DE becomes the draw destination (old HL handed back in DE), then stamp a 2x2 tile block from the seed tile in A at that VRAM cell.", cert: "code" },
  0x219b: { name: "blank4x4AndDraw2x2Icon", role: "[code] Indicator form 0: clear the 4x4 tile block (blankTileBlock4x4) then overlay a 2x2 icon seeded with tile 96 at loc_51fc.", cert: "code" },
  0x2261: { name: "drawBcdNumberColumn", role: "[code] Paint three packed-BCD bytes (walked downward from the DE source) as six digit tiles up the IX VRAM column -- high nibble then low per byte, stepping the cursor one row up (-32) per digit -- with a 4-digit leading-zero blank budget via drawBcdDigit; callers point it at the score/high-score VRAM fields.", cert: "code" },
  0x2583: { name: "drawFixedTileBlock2x2", role: "[code] Stamp a 2x2 tile block at the HL destination seeded from the fixed glyph code 44 (0x2c), laying tiles 0x2c..0x2f; the block form of the fixed 0x2c glyph family.", cert: "code" },
  0x2593: { name: "drawTileBlock2x2Up", role: "[code] Draw a 2x2 tile block growing upward from HL: a top pair (tile, tile+1) via stampTilePair with a -33 net stride, then a bottom pair seeded four codes lower one row above; preserves DE. The upward counterpart of drawTileBlock2x2.", cert: "code" },
  0x1344: { name: "launchAttackerFromFormation", role: "[code] One-shot on SUBCOUNTER_REFILL_FLAG (0x4228, consumed): while region-clear gate 0x4220 bit0 is clear, derive a 1..4 slot budget from the pace counter (0x421a+0x421b), claim the first both-bytes-zero object slot scanning down from 0x4391 (stride 31), stamp the launch direction (0x4215) into slot+6, scan COLUMN_OCCUPANCY for an occupied column by direction, walk that FLAG_BITS_BASE grid column for a filled cell, clear the cell, activate the slot (byte0=1, phase byte2=0, slot+7=cell-low), and enqueue a type-1 spawn command word. Launches one new diving attacker out of the standing formation when the pace/refill timer fires.", cert: "code" },
  0x0b0b: { name: "flagPlayerShotHitOnFormation", role: "[code] Player-shot vs formation collision (called from the runGameplayFrameAndAdvanceOnFieldClear per-frame pipeline): while the shot gate 0x4208 bit0 is armed, band the shot Y (0x4209) into a formation row and the shot X-delta (0x420a minus formation anchor 0x420e) into a column, index the FLAG_BITS_BASE grid; if that cell holds a live alien clear it, stamp a hit record (0x420b=1, 0x42b1=1, 0x42b2=0, 0x42b3=shot position word), and enqueue two command words (kind 1 with the grid index, kind 3 with a column code). Registers the player shot destroying a formation alien and queues its kill/scoring/sound events.", cert: "code" },
  0x090d: { name: "advanceFormationSweepOscillator", role: "[seen] Per-frame formation sway: once every 4 frames step the swept 16-bit formation word 0x420e one unit toward the FORMATION_X_BOUNDS pair, flipping OBJ_SWEEP_DIRECTION (0x420d) at each bound via setSweepDescending (0x097d, upper bound) / setSweepAscending (0x0983, lower bound), then broadcast the negated low byte across the strided per-column table; a leading proximity gate (armed shot lined up on the swept column, that column occupied) shortcuts straight to broadcastNegatedFormationSweepToStridedTable. Drives the whole alien formation's side-to-side oscillation.", cert: "seen" },
  0x00e6: { name: "fillScreenThenLatchConfigAndAdvanceState", role: "[seen] Game-state-0 boot handler (dispatch slot 0 of loc_0066's game-state table {0x00e6,0x0156,0x03f2,0x0536,0x077b}): each frame fills a 32-byte VRAM tilemap block at the write cursor (0x400b/0x400c) with the blank tile and advances the cursor across 0x5000-0x53ff while per-state timer 0x4008 counts down; on expiry resets the state cluster (0x4006=0, 0x4007=1, GAME_STATE 0x4005=1, SEQUENCE_STATE 0x400a=0), latches config bits from the input/DIP shadows into 0x4000/0x401f/0x400f and a coinage-table byte into 0x40ac, unpacks the packed flag bitmask, seeds the object shadow and the player-1 status glyphs, and enqueues two deferred command words.", cert: "seen" },
  0x0e20: { name: "commitMoveToStoredOrPlayerTargetX", role: "[code] Alternate horizontal target-select branch: if OBJ_TABLE (0x42d0) bit0 is set, commit the actor toward the object-table's stored target X (OBJ_TABLE+0x19) via commitMoveToTargetX (0x0df6); otherwise run the player-crossover pick via commitMoveAcrossPlayerX (0x0ddd). Chooses an attacking object's next horizontal target.", cert: "code" },
  0x0d06: { name: "initSpawnedObjectFromGridCell", role: "[code] Object-AI spawn-init handler (dispatch slot 0 of the 0x0ce6 object-AI table; siblings advanceObjectPathStep 0x0d71, advanceObjectDiveStep 0x0e6b, reseedFormationObjectState 0x0e99): clear the step timer (ix+23), raise spawn flag 0x41c2, derive the sprite position from the packed grid cell (positionObjectFromGridCell), enqueue a type-1 spawn command word, look up sprite# and flight-curve seed from SPAWN_RECORD_TABLE (0x1dd1) by row (top row also tallies its two active neighbour slots into ACTIVE_NEIGHBOR_COUNT 0x422a), seed the motion counters, advance the sub-state, and set the signed heading from the direction bit. First-tick initialization of a freshly-launched attacker object.", cert: "code" },
  0x145c: { name: "activateObjectSlotAndEnqueueSpawn", role: "[code] Activate a claimed free object slot: consume the trigger flag it was found under (write 0 at HL), mark the slot at IX active (byte0=1, phase byte2=0), record the spawn code (C -> byte6) and the trigger pointer's low byte as the source index (byte7), then enqueue a type-1 spawn command word keyed by that source index; returns the trigger pointer unchanged for the caller. Tail/called from the free-slot finders spawnIntoFreeDescriptorSlot, spawnPrimaryAndSecondaryObjects, spawnObjectsFromTriggerFlags (IX=0x42d0).", cert: "code" },
  0x1637: { name: "advanceStageAndReseedFormation", role: "[code] On the armed stage-advance one-shot (enable 0x4222 bit0 + countdown 0x4223 hitting zero): disarm the enable, rebuild the 128-flag formation block from the packed template, reseed the formation anchor 0x420e, step the stage selector 0x421b (low byte saturating at 7, high byte counting), enqueue a command word, and service a pending two-slot request 0x421e -> 0x4177/0x4178.", cert: "code" },
  0x1ccf: { name: "drawTextColumnByIndex", role: "[code] Index the 5-byte text-descriptor table (TEXT_DESCRIPTOR_TABLE) by A and paint that descriptor's on-screen text column via drawTextColumnFromDescriptor.", cert: "code" },
  0x20a7: { name: "repaintPlayerStatusColumnIfSaved", role: "[code] Repaint the player-status VRAM column via repaintPlayerStatusColumn, but only when the saved status byte 0x40ab is nonzero; a zero saved byte returns without painting.", cert: "code" },
  0x0430: { name: "holdStartLampsThenAdvanceSequence", role: "[code] runStartScreenAndLaunchGame sub-state slot 1: tick countdown 0x4019, and while it stays nonzero keep the start-button lamps in step with credits (driveStartButtonLamps); on its zero-cross advance SEQUENCE_STATE (0x400a) and clear the 128-byte flag-bits block.", cert: "code" },
  0x0605: { name: "advanceSubstateAfterDwellAndQueue", role: "[code] Play sub-state timer (dispatch slot 3 of loc_0536 and loc_077b): tick dwell timer 0x4009; on its zero-cross reload it to 20, advance SEQUENCE_STATE (0x400a), and enqueue this state's command word (0x0682).", cert: "code" },
  0x0795: { name: "restoreSavedStateAndEnterPlaySubstate", role: "[code] loc_077b sub-state slot 2: expand the saved formation snapshot (SAVED_STATE_SNAPSHOT 0x41a0) into the flag block, copy the trailing 8-byte template into 0x4218, clear 0x425f/0x4220, mirror the flip flag 0x400f into the FLIP_SCREEN_X/Y latches when set, advance SEQUENCE_STATE, arm state timer 0x4009=150, publish the sub-state pointer into 0x4245, and enqueue five intro command words when the sound gate 0x4006 bit0 is open.", cert: "code" },
  0x2591: { name: "drawFixedTileBlock2x2Up", role: "[code] Draw a 2x2 tile block upward from the pointer using the fixed decorative tile seed 46 (drawTileBlock2x2Up); used by drawMarkerRow to blank unused marker-row slots.", cert: "code" },
  0x0722: { name: "advanceDwellOrResetToState1", role: "[code] Shared tail of state-6 handlers stepPlaySubstate6/stepAltPlaySubstate6: when mode flag 0x4006 bit0 is clear, advanceSubstateAndReloadDwell (advance the sub-state counter at HL, reload the dwell timer); when set, reset to state 1 -- GAME_STATE (0x4005)=1, clear 0x4006 and SEQUENCE_STATE (0x400a), silenceSoundAndDisableIrqStars, then enqueue command word 6.", cert: "code" },
  0x12ed: { name: "handlePlayerHitEvent", role: "[code] Sole consumer of HIT_EVENT_FLAG (0x4204, raised by flagProjectileHitOnPlayer 0x0b8d when an enemy shot overlaps the player); called from the per-frame pipeline runGameplayFrameAndAdvanceOnFieldClear. If bit0 clear, no-op; else clear it, zero OBJ_ACTIVE_FLAG (0x4200) and set 0x4201=1, arm pulse counters 0x4205=10/0x4206=4 (the exact pair driveGatedSoundStepSequence ticks down), enqueue the hit sound command (2,5), decrement pace counter 0x421a (floored at 0), step the [0,5] cycle counter 0x421d, and pulse SOUND_W_REG3=1 when 0x4006 bit0 is set.", cert: "code" },
  0x1801: { name: "stageSoundPitchBySelector", role: "[code] Pitch-selector dispatcher, tail-called from the sound-counter managers advanceSoundSweepAndStagePitch/tickSoundCounterAndStagePitch: reads (HL)&0x03; a nonzero selector -> stagePitchFromSoundCounter(selector) (warble recomputed from sound counter 0x41c4), zero -> stageSoundPitch(96) (fixed pitch). Both delegates stage SOUND_PITCH (0x41c1).", cert: "code" },
  0x194f: { name: "incrementCreditCount", role: "[code] Step the credit count at (HL) (both callers tickCoinMeterAndAwardCredits/awardCreditEverySecondCoin pass 0x4002) toward the 99 ceiling: ==99 return; >99 clampCreditsToMax (pin to 99); else increment, set ready flag 0x41c9=1 (arms driveRisingPitchRamp), and enqueue command word (7,1). 0x4002 as credit count is corroborated by clampCreditsToMax/driveStartButtonLamps/advanceGameStateOnCredit.", cert: "code" },
  0x01e1: { name: "fillVramRowThenResetObjectState", role: "[seen] loc_0156 sequence sub-state 3 (rst-28 table @0x0164): each frame fills a 28-cell strip of tile 16 at VRAM_WRITE_PTR (0x400b) and advances the cursor +32 (one row); ticks dwell tier 0x4009; on its expiry increments SEQUENCE_STATE (0x400a), re-arms the dwell cascade (0x4008=64, 0x4009=4), clears the 48-byte OBJ_ACTIVE_FLAG block, clears FLIP_SCREEN_X/Y and 0x4018, sets 0x4238=1, and reseeds the object-shadow field from ROM template 0x1db1.", cert: "seen" },
  0x1327: { name: "driveGatedSoundStepSequence", role: "[code] Per-frame play-pipeline ticker (runGameplayFrameAndAdvanceOnFieldClear) gated by 0x4201 bit0 (armed by handlePlayerHitEvent/handlePlayerHitEvent with 0x4205=10, 0x4206=4): prescaler 0x4205 (reload 10) fires once per 10 eligible frames, enqueuing command word (2, step=0x4206) and decrementing the step; when 0x4206 drains, disable (0x4201=0) and silence SOUND_W_REG3 (0x6803=0).", cert: "code" },
  0x1d43: { name: "drawScreenFillStripSecondHalf", role: "[code] Second half of the tile-strip fill (fallen into from drawScreenFillStripFirstHalf, which stamps tile pair 0x30/0x32 and sets B=0x10): stamps B pairs of tiles 52/54 forward from the cursor (HL, two cells per pass, count 0 wraps to 256), saves the advanced cursor to VRAM_WRITE_PTR (0x400b), ticks strip dwell 0x4008; on its expiry restartScreenFillOnDwellExpiry(0x4008).", cert: "code" },
  0x2146: { name: "drawIndexedTileBlock", role: "[code] Look up a 2x2 tile-block code in TILE_BLOCK_TABLE (0x215b) by index, then stamp that block at the pending VRAM destination via drawTileBlock2x2AtDe.", cert: "code" },
  0x029d: { name: "blankVramRowThenResetSpriteState", role: "[code] loc_0156 sequence-state handler (state index 9): each tick clear the strided table and blank a 28-cell row of tile 16 at VRAM_WRITE_PTR (step cursor +32); on dwell (0x4009) expiry advance SEQUENCE_STATE, clear SPRITE_SOURCE_OBJ_BASE (256B) and SPRITE_SHADOW_BASE (64B), re-arm the two-tier dwell (0x4008=64,0x4009=4), reseed the object shadow, and queue command word 6.", cert: "code" },
  0x05e2: { name: "enqueueCommandWordBurst", role: "[code] Post a five-word burst into the command queue via enqueueCommandWord: (D,2),(D+1,2),(D+1,4),(7,3),(7,0), each word (channel<<8)|param with D=caller's channel. Tail of restoreFormationAndEnterPlaySubstate (falls through after 0x0500) and entered from queueBoardStartSoundBurst.", cert: "code" },
  0x149b: { name: "spawnSecondaryObjectIntoSlot", role: "[code] Called per-slot from spawnSecondaryObjectAndAdvanceWalk's spawn walk (IY stepped by 0x20): if neither of the IY slot's two live flags (byte0 bit0 / byte1 bit0) is set, consume the trigger flag at HL (set 0), mark the slot alive (byte0=1), clear its state (byte2=0), inherit field 6 from the IX source record, stash the trigger index (byte7), and enqueue activation command (1<<8)|index.", cert: "code" },
  0x1898: { name: "driveSoundLfoLevel", role: "[code] Per-frame LFO-level driver called from loc_0066 (VBLANK-NMI): with no reset request (SOUND_LFO_RESET_REQUEST 0x41d0 == 0) run decaySoundLfoLevel; otherwise consume the request (clear 0x41d0) and slam full level (15) across the LFO frequency latches via broadcastSoundLfoLevel.", cert: "code" },
  0x02e8: { name: "clearFlagBlockAndReseedObjectShadow", role: "[code] loc_0156 sequence-state handler (state index 12): zero-fill the 128-byte FLAG_BITS_BASE block (0x4100), clear status cells 0x425f and 0x4238, arm the mid-tier dwell (0x4009=64), then advance SEQUENCE_STATE and reseed the stride-2 object-RAM shadow via advanceSequenceStateAndReseedObjectShadow.", cert: "code" },
  0x0f07: { name: "settleObjectIntoFormationCell", role: "[code] Object-AI state handler (slot 6 of the 0x0ce6 rst-28 jump table, dispatched on record+2): bump the frame counter (record+3), reposition from the packed grid cell (positionObjectFromGridCell), then when the counter reaches the positioned value deactivate the object (record+0=0), set its formation-cell flag FLAG_BITS_BASE+cell=1 and enqueue command word {0:cell}; a small even gap nudges phase (record+5) by the direction bit (record+6), a large (>=25) or odd gap is left alone.", cert: "code" },
  0x184f: { name: "advancePulseToneEnvelope", role: "[code] sound-envelope word tick (called per-frame by the sound driver driveSoundFrame, 0x170c slot): if the 0x41c7/0x41c8 word's low-byte bit0 is set, re-arm the word to its 0x8000 sentinel (0x41c7=0, 0x41c8=128); else hand the high byte to pulseSoundToneFromCountdown (0x185e) to stage the pulsed tone.", cert: "code" },
  0x2104: { name: "computeTileVariantFromValueAndTimer", role: "[code] register-compute: bias a value (B) into a timer-animated 2-bit tile-variant index -- saturate to the 0x80 out-of-range marker at/above 112, else fold the value's low nibble with a carry set when the frame counter (0x425f) low nibble is smaller, via computeTileVariantFromTimer (0x211d). Live-out B; no memory write.", cert: "code" },
  0x018c: { name: "initSequenceEnableStarfield", role: "[seen] loc_0156 sequence sub-state 0 setup: enqueue two setup command words, enable the starfield (STARS_ENABLE 0x7004) and set 0x4007, reset per-sequence cells (CURRENT_PLAYER 0x400d, 0x400e, 0x4006, 0x4019), seed the dwell cascade (0x4008=96, 0x4009=16), and advance SEQUENCE_STATE (0x400a).", cert: "seen" },
  0x0443: { name: "blankVramRowsThenDriveStartLamps", role: "[code] runStartScreenAndLaunchGame sequence state index 2: fill two 28-cell blank-tile (16) rows through VRAM_WRITE_PTR (skipping a 4-cell gap between rows) and store the advanced cursor, then tick the dwell tier 0x4009; while rows remain, return. On the last row: advance SEQUENCE_STATE (0x400a), clear FLIP_SCREEN_X/Y and the 0x4018 direction flag, enqueue two command words, and call driveStartButtonLamps (0x0473).", cert: "code" },
  0x10c2: { name: "advanceObjectAndQueueMessageColumn", role: "[seen] object-AI state 14 (driveObjectSlot state table idx 14, table @0x0ce6): bump the object record's tick (ix+4) and count down its dwell timer (ix+16); while it runs, return. On expiry, enqueue a channel-6 command word carrying the object's payload selector (ix+7 + 75), dispatched to renderMessageColumn (0x22f1), and advance the object state (ix+2).", cert: "seen" },
  0x2256: { name: "drawScoreToSelectedPlayerField", role: "[code] select the VRAM score-digit field cursor by selector A (0 -> DIGIT_FIELD_PRIMARY 0x5381, else DIGIT_FIELD_ALT 0x5121), then paint the packed-BCD number column (source DE) into it via drawBcdNumberColumn (0x2261). No work-RAM write.", cert: "code" },
  0x0408: { name: "resetObjectRamAndAdvanceSequence", role: "[code] runStartScreenAndLaunchGame sequence state index 0: seed the stride-2 OBJRAM shadow from ROM template 0x1d91, zero the sprite-shadow span (0x4060, 64 bytes) and the object-record region (0x4260, 256+80 bytes), clear 0x4238 and MESSAGE_SCROLL_ENABLE (0x40b0), set VRAM_WRITE_PTR to VRAM_BASE+2, arm dwell tier 0x4009=16, and advance SEQUENCE_STATE (0x400a).", cert: "code" },
  0x125e: { name: "awardKillScoreByBandAndDeactivate", role: "[code] Deactivate the hit object (slot[0]=0,[1]=1,[2]=0) and award a kill score sized by which of 3 bands its position/type field (obj+7) falls in vs threshold 0x50; on band-exhaust raise inhibit word 0x422b=0xf001, fold a neighbour bonus when ACTIVE_NEIGHBOR_COUNT(0x422a)==2 (record at 0x422d), and enqueue the channel-3 score-add command (BCD score handler 0x21a6).", cert: "code" },
  0x191e: { name: "addCreditForCoin", role: "[code] Coin-service credit bump (serviceCoinInputs bit7 branch): if credit count 0x4002 < 99 increment it, raise event flag 0x41c9=1, and tail-enqueue a channel-7 command that redraws the credit-count HUD (dispatch 0x24b7 arg 1 renders 0x4002 capped at 99 as two BCD digits); at the 99 cap do nothing.", cert: "code" },
  0x205e: { name: "drawFixedTileFigureAtPackedCoord", role: "[code] Channel-1 display-list draw handler (jump table 0x203d): map the packed coordinate to its VRAM cell (mapPackedCoordToVram) and stamp a fixed 0x2c-family tile figure there — a 2x2 tile block when coord bit4 is set, else a vertical tile pair.", cert: "code" },
  0x0218: { name: "emitMessageColumnsThenAdvanceSequence", role: "[seen] loc_0156 sequence-state handler (rst-28 dispatch table @0x0164, state 4): run clearStridedTable, then a two-tier dwell (prescaler 0x4008 / dwell 0x4009) — each low-tier expiry reloads it to 80 and enqueues a channel-6 renderMessageColumn command (index = mid count + 6); on mid-tier expiry advance SEQUENCE_STATE(0x400a), reload both tiers (32/4), clear SPRITE_SOURCE_OBJ_BASE(0x42b0) and DRAWN_COLUMN_COUNT(0x4241).", cert: "seen" },
  0x04bc: { name: "startGameRoundAndClearScores", role: "[code] Game/round-start entry (fall-through from beginGameOnStartButton, jp from startOnePlayerGame): store the player-count/spawn word in CURRENT_PLAYER(0x400d), blit the 32-byte ROM row template 0x051b into PACKED_FLAG_BITMAP(0x4180), arm the substate-advance gate when 0x401f bit0 is set, enter play (GAME_STATE=3, SEQUENCE_STATE=0, 0x4006=1, 0x41d1=1), and queue a start message (ch6) plus two channel-4 score-slot clears.", cert: "code" },
  0x0583: { name: "blankScreenRowsThenAdvanceSequence", role: "[code] Play-state sub-state-1 progressive screen clear (state 1 of both play tables loc_0536/loc_077b): blank 32 VRAM cells (tile 16) at VRAM_WRITE_PTR(0x400b), advance the cursor +32, tick phase counter 0x4009; on the last phase advance the sequence and reseed the OBJRAM shadow (advanceSequenceStateAndReseedObjectShadow).", cert: "code" },
  0x21f8: { name: "drawHighScoreDigits", role: "[code] Paint the high-score number: set the VRAM cursor to field 0x5241 and draw 6 packed-BCD digits from the caller's source pointer (drawBcdNumberColumn); reached from the high-score update tail loc_21a6 (after a higher total is copied to 0x40a8) and the opcode-5 high-score redraw drawScoreFieldByIndex.", cert: "code" },
  0x02d1: { name: "postCreditAndMessageDrawsAndAdvance", role: "[code] Sequence-state handler: enqueue a channel-7 (arg 1) credit-count redraw and a channel-6 (arg 0) message-column draw, increment SEQUENCE_STATE (0x400a), and re-arm both dwell-timer tiers (0x4008=96 sub-timer, 0x4009=16 mid-tier).", cert: "code" },
  0x0614: { name: "activateObjectsAndBeginPlayPhase", role: "[code] State-timer handler: tick dwell 0x4009; while nonzero return. On expiry reload 0x4009=10, advance SEQUENCE_STATE, set OBJ_ACTIVE_FLAG (0x4200)=1 to enable the object/AI/projectile subsystem, seed player-X reference 0x4202=128, refill the 16-byte enemy-launch sub-counter block 0x424a from SUBCOUNTER_RELOAD_TABLE (0x15e3), clear scratch 0x4058/0x405a, and enqueue channel-7 (arg 3) and channel-2 (arg 0, the 4x4 indicator draw) display commands.", cert: "code" },
  0x0f7b: { name: "beginObjectCrossPlayerMove", role: "[code] Shared object-AI tail: call commitMoveAcrossPlayerX (0x0ddd) to pick and commit a horizontal target on the far/opposite side of the player-X reference, then arm the object's flight-curve step seed record+0x18=3 (-> (3&3)+1 = 4 curve steps in advanceObjectFlightCurve 0x116b) and its move throttle record+0x10=100.", cert: "code" },
  0x215f: { name: "draw4x4TileForm", role: "[code] Display-list channel-2 handler: draw one of three 4x4-tile forms at a fixed VRAM region selected by the command arg -- form 0 blanks the block then overlays a 2x2 icon (blank4x4AndDraw2x2Icon 0x219b), form 1 just blanks it (blankTileBlock4x4 0x2187), else fold (form-2) into a complemented tile code over base 0xc0 and stamp four 2x2 tile blocks at 0x51da/0x51dc/0x521a/0x521c (a contiguous 4x4 cell region, seed +4 per block, via drawTileBlock2x2 0x2585).", cert: "code" },
  0x04f2: { name: "startOnePlayerGame", role: "[code] One-player game-start arm (beginGameOnStartButton bit0 path): spend one credit (0x4002--), zero the saved-state snapshot 0x41a0, and enter play via startGameRoundAndClearScores with spawn word 0 (GAME_STATE=3, single player); no credit -> force GAME_STATE=1. Own write is only the credit spend (0x4002, itself [code]); the start is delegated, so not write-grounded", cert: "code" },
  0x05fc: { name: "queueBoardStartSoundBurst", role: "[code] Board/level-start sound cue, paired-player variant (sole caller restoreFormationAndEnterPlaySubstate when sound gate 0x4006 bit0 and paired-player flag 0x400e bit0 are set): enqueue a prologue command word (channel 5, param 3) then the standard channel 5/6/7 burst via enqueueCommandWordBurst", cert: "code" },
  0x06d8: { name: "stepPlaySubstate6", role: "[code] Play sub-state slot 6 handler (loc_0536, game-state 3): by arm gate 0x421d and mode flags 0x41b5/0x400e, advance or redirect SEQUENCE_STATE (0x400a) and reload dwell timer 0x4009 (=130 on the inline advance), queuing two channel-6 command words when 0x4006 bit0 is set; shared reset tail advanceDwellOrResetToState1", cert: "code" },
  0x07e8: { name: "stepAltPlaySubstate6", role: "[code] Alternate play sub-state slot 6 handler (loc_077b, game-state 4, restore-saved-formation path); mirror of stepPlaySubstate6 keyed on advance gate 0x4195 + arm gate 0x421d: advance/redirect SEQUENCE_STATE (0x400a) and reload dwell 0x4009 (=80 or 130), queuing two channel-6 command words on the default inline advance", cert: "code" },
  0x0dd1: { name: "advanceActorPhaseAndCommitMove", role: "[code] Object-AI state-2 handler (0x0ce6 state table, index 2): tick the actor phase counter ix+3, then commit its next horizontal move -- kind (ix+7)&0x70==0x60 -> commitMoveToStoredOrPlayerTargetX, else commitMoveAcrossPlayerX (target relative to reference X 0x4202)", cert: "code" },
  0x0f66: { name: "armDirectedMoveWhenInWindow", role: "[code] Object-AI state-8 handler: tick arm counter ix+3; while ix+3 or position ix+4 is outside [0x60,0xA0) keep cruising cross-player (beginObjectCrossPlayerMove); once both in-window advance state ix+2 by 2, seed move timers ix+0x10=3/ix+0x11=12, clear ix+5/ix+0x13, and set direction ix+6 from the reference-X (0x4202) compare", cert: "code" },
  0x1091: { name: "restartObjectMoveRun", role: "[code] Object-AI state-12 handler: tick sub-counter ix+3, force state ix+2=8 (re-enter the arm-window state armDirectedMoveWhenInWindow), and begin a fresh cross-player horizontal move (beginObjectCrossPlayerMove)", cert: "code" },
  0x123f: { name: "flagPlayerShotHitOnObject", role: "[code] Per-object hit test: for an active object at IX, box-test its position (ix+3/ix+4) against the player-shot reference (0x4209/0x420a) inside a 6-wide x 12-tall window; on overlap raise shot-retire flag 0x420b=1 and tail-call awardKillScoreByBandAndDeactivate to score+deactivate the object. Sibling of flagPlayerShotHitOnFormation (0x0b0b).", cert: "code" },
  0x12b6: { name: "flagObjectHitOnPlayer", role: "[code] Per-object player-collision test: for an active object at IX, classify (ix+3)+0x21 into a near (<5) or far (<0x11) window and test player-X reference 0x4202 minus (ix+4) against the window's band (near +7/0x0f, far +0x0a/0x15); on overlap raise HIT_EVENT_FLAG 0x4204=1 (consumed by handlePlayerHitEvent 0x12ed) and tail-call awardKillScoreByBandAndDeactivate.", cert: "code" },
  0x1446: { name: "spawnIntoFreeDescriptorSlot", role: "[code] Free-slot finder: scan the 4 descriptor slots at DESCRIPTOR_SLOT_TABLE (0x4330) high->low (stride 32) for one whose two guard bytes are both zero; on a hit tail-call activateObjectSlotAndEnqueueSpawn(trigger,slot,spawnCode) to seed the slot and enqueue its spawn word; no free slot -> no-op. Reached from spawnObjectsOnDelayedEvent/spawnObjectsFromTriggerFlags.", cert: "code" },
  0x148e: { name: "spawnSecondaryObjectAndAdvanceWalk", role: "[code] Per-slot step of the secondary-object spawn walk: spawn into the current IY slot via spawnSecondaryObjectIntoSlot (0x149b), advance IY by 32 to the next record and decrement the C budget; when the budget reaches 0 also force the caller's B loop counter to 1 so the enclosing walk ends after this pass. Called from spawnPrimaryAndSecondaryObjects/spawnObjectsFromTriggerFlags.", cert: "code" },
  0x17f9: { name: "tickSoundCounterAndStagePitch", role: "[seen] Sound-counter tick tail (entered by fall-through from advanceSoundSweepAndStagePitch): when the count in A is nonzero, decrement sound-counter 0x41c4 and store it back, then tail-call stageSoundPitchBySelector to stage the pitch keyed on (HL)&3.", cert: "seen" },
  0x18ef: { name: "serviceCoinInputs", role: "[seen] Per-frame coin/input service front-end (first in loc_0066's service cluster): in config mode 3 (0x4000==3) delegate to presetCreditCount; else combine input shadows (IN0_SHADOW 0x4010 | 0x4013), complement, and mask by guard cells 0x4015 & 0x4016 -- bit7 set -> addCreditForCoin; else the low two bits each tick coin-pulse counter 0x4004 (up to twice).", cert: "seen" },
  0x1964: { name: "awardCreditEverySecondCoin", role: "[code] Two-coins-per-credit path (mode-1 arm of coin dispatcher tickCoinMeterAndAwardCredits): if coin-phase flag 0x4001 bit0 is clear (first coin of a pair) delegate to setCoinPhaseFlag to raise it; if already set (second coin) clear 0x4001 and delegate to incrementCreditCount(0x4002) to award one credit.", cert: "code" },
  0x1c73: { name: "drawInputTextColumnsAndSeedScreenFill", role: "[seen] Attract/reset init: decode three 2-bit input-port fields (IN1 6-7, IN2 0-1, IN2 2) into text-descriptor indices and paint each column, then (unless IN0 bit6 is set) seed the screen-fill state (0x4006=0, 0x401a=2, dwell pair 0x4008/0x4009=0x3010, VRAM_WRITE_PTR 0x400b=VRAM_BASE), clear the 4-byte start-lamp/coin latch block, and silence the sound hardware.", cert: "seen" },
  0x1d39: { name: "drawScreenFillStripFirstHalf", role: "[code] First half of the animated screen-fill tile strip: stamp `count` two-tile pairs (48,50) forward from the VRAM cursor (two cells per pass, count 0 wraps to 256), then fall into drawScreenFillStripSecondHalf which stamps 16 more pairs and ticks the strip dwell.", cert: "code" },
  0x209c: { name: "repaintPlayerStatusColumnFromModeGate", role: "[seen] Repaint the player-status column while latching the mode gate: when mode byte 0x4006 is nonzero, save it into the repaint-gate byte 0x40ab and repaint the column; when 0x4006 is zero, repaint only if 0x40ab is already set.", cert: "seen" },
  0x213d: { name: "drawSelectedTileBlockOrFallback", role: "[code] Select a 2x2 tile block by the signed selector B: non-negative -> look the block up in the tile-block table by that index and stamp it at the pending DE destination; negative -> stamp the fixed fallback block (tile 0xa4) there.", cert: "code" },
  0x2231: { name: "drawScoreFieldByIndex", role: "[code] Redraw the packed-BCD score column selected by counter index: 0 -> player-1 score (primary field), 1 -> player-2 score (drawn only when the live flag 0x400e is set, which also picks the alt field), 2 -> high score; index >=3 recurses down, redrawing every field from index-1 to 0.", cert: "code" },
  0x22b3: { name: "drawMarkerRow", role: "[code] Redraw the 5-slot marker row at MARKER_ROW_VRAM (0x539e): paint `markers` marker tiles (102) growing upward, then blank the remaining slots until the signed slot counter goes negative; when OBJ_ACTIVE_FLAG (0x4200) is set the displayed count is dropped by one, and if that empties it every slot is blanked instead.", cert: "code" },
  0x0492: { name: "beginGameOnStartButton", role: "[code] Start-button round launcher: IN1_SHADOW bit0 begins a one-player game (tail to startOnePlayerGame); bit1 with >=2 credits spends two, blits the 32-byte ROM row template into SAVED_STATE_SNAPSHOT (0x41a0), optionally arms the state-advance gate on config 0x401f bit0, and enters startGameRoundAndClearScores with the 2-player spawn word.", cert: "code" },
  0x05a5: { name: "restoreFormationAndEnterPlaySubstate", role: "[seen] Game-state-3 sequence dispatch slot 2 (board/level-start): unpack the packed flag bitmap (0x4180) into the flag grid via unpackBitmaskToFlagBytes, copy the trailing 8-byte board template into 0x4218, reset status/flip/direction cells (0x425f/0x4220/0x4018=0), advance SEQUENCE_STATE, arm the 150-tick dwell timer 0x4009, publish deferred-callback pointer 0x0640 into 0x4245, then cue the board-start sound when the sound gate is open.", cert: "seen" },
  0x1227: { name: "flagPlayerShotHitsOnObjects", role: "[code] Player-shot vs object-table sweep: when the shot gate 0x4208 bit0 is armed, box-test the shot reference (0x4209/0x420a) against each of the 7 object records (OBJ_TABLE 0x42d0, stride 0x20) via flagPlayerShotHitOnObject, scoring and deactivating any it overlaps. Gate clear -> no-op.", cert: "code" },
  0x129e: { name: "flagObjectHitsOnPlayer", role: "[code] Object vs player collision sweep: when the object subsystem 0x4200 bit0 is enabled, box-test each of the 7 objects (OBJ_TABLE 0x42d0, stride 0x20) against the player-X reference 0x4202 via flagObjectHitOnPlayer, raising HIT_EVENT_FLAG (0x4204) on any overlap. Disabled -> no-op.", cert: "code" },
  0x1472: { name: "spawnPrimaryAndSecondaryObjects", role: "[code] Spawn a primary object into OBJ_TABLE (0x42d0) via activateObjectSlotAndEnqueueSpawn, then walk 3 trigger flags backed up (-0x0f) from the primary trigger's low byte and, for each set flag, spawn a secondary into the next slot (from 0x42f0) until a budget of 2 is spent.", cert: "code" },
  0x14be: { name: "spawnObjectsFromTriggerFlags", role: "[code] Scan the primary trigger block (0x4176, 4 flags): first set flag spawns a primary into OBJ_TABLE via activateObjectSlotAndEnqueueSpawn plus up to 2 secondaries from the secondary block (0x4165) via spawnSecondaryObjectIntoSlot; if no primary flag is set, scan the secondary block and on the first set flag seed a free descriptor slot via spawnIntoFreeDescriptorSlot.", cert: "code" },
  0x17e5: { name: "advanceSoundSweepAndStagePitch", role: "[code] Sound-counter manager head: early-return while gate 0x4226 bit0 is set; else step the pointer forward one cell; if gate 0x425f bit0 is set hand straight to stageSoundPitchBySelector; otherwise bump the pointed sweep cell (0x41c3) while sound counter 0x41c4 < 96, then fall into tickSoundCounterAndStagePitch, ultimately staging SOUND_PITCH (0x41c1).", cert: "code" },
  0x1931: { name: "tickCoinMeterAndAwardCredits", role: "[seen] Per-frame coin/credit service tick: while reload cell 0x4003 counts down pulse the coin-counter, and on expiry decrement coarse coin counter 0x4004, refill 0x4003=15, then award credit(s) to credit count 0x4002 per coinage mode 0x4000.", cert: "seen" },
  0x1c68: { name: "armInputFlagAndDrawInputColumns", role: "[code] Input-scan link: fold the two input-port bytes and, when their shared bit4 is set, raise companion input flag 0x41cc=1, then tail-delegate to drawInputTextColumnsAndSeedScreenFill (attract/reset input-column draw + screen-fill seed).", cert: "code" },
  0x1d28: { name: "advanceScreenFillStrip", role: "[code] Head of the per-frame tile-strip screen-fill: pet the watchdog, read strip gate 0x4008 -- if zero restart the outer fill dwell (restartScreenFillOnDwellExpiry), else load VRAM write cursor 0x400b and draw the strip's first half (drawScreenFillStripFirstHalf).", cert: "code" },
  0x2131: { name: "drawTileGlyphOrBlock", role: "[code] Tile-figure draw dispatch keyed on carry: carry set stamps a 2x2 tile block selected by B (drawSelectedTileBlockOrFallback, fallback tile 0xa4 when B negative); carry clear fetches B's tile code from table 0x2157 and paints a double-height glyph at HL (drawDoubleHeightTile).", cert: "code" },
  0x21fe: { name: "clearAndRedrawScoreField", role: "[seen] Clear the packed-BCD score field selected by index A (0=P1 0x40a2, 1=P2 0x40a5, 2=high 0x40a8) -- zero its three digit bytes plus the per-player bonus companion (0x40ad/0x40ae; high score re-zeros its own first byte) -- then repaint via drawScoreFieldByIndex; index>=3 descends over all lower fields.", cert: "seen" },
  0x229c: { name: "awardBonusMarker", role: "[code] One-shot per current player (guard flag table 0x40ad indexed by CURRENT_PLAYER 0x400d): on the first score-threshold trip flag the player's slot, raise sound-envelope trigger 0x41c7=1, increment marker counter 0x421d, and repaint the marker row (drawMarkerRow).", cert: "code" },
  0x140c: { name: "spawnObjectsOnDelayedEvent", role: "[code] Delayed-spawn dispatcher (per-frame from update pipeline runGameplayFrameAndAdvanceOnFieldClear): gated on region-clear 0x4220 bit0 clear, OBJ_ACTIVE_FLAG 0x4200 bit0 set, and DELAYED_EVENT_REQUEST 0x4229 bit0 set (consumed as a one-shot), and only while the OBJ_TABLE 0x42d0 head word is even; then route by launch direction 0x4215 bit0 -- set = full trigger-block spawn (spawnObjectsFromTriggerFlags 0x14be), else scan the primary trigger block 0x4176.. high->low (spawnPrimaryAndSecondaryObjects 0x1472), then the secondary window (spawnIntoFreeDescriptorSlot 0x1446).", cert: "code" },
  0x17d0: { name: "updateSoundSweepVoice", role: "[code] Per-frame sound-sweep voice updater (2nd of the sound-driver tick driveSoundFrame's channel/effect updaters): gated on 0x4006 bit0; while its counter cell 0x41c2 != 1 delegate to the sound-counter manager advanceSoundSweepAndStagePitch (steps sweep cell 0x41c3 while sound counter 0x41c4 < 96 ceiling, stages SOUND_PITCH 0x41c1); on the tick where 0x41c2 == 1, reload the idle template -- 0x41c2=0, 0x41c3=2, 0x41c4=160 (counter parked past the 96 ceiling so the sweep stops bumping until it decays). Own writes are only that constant idle-template reload (grounds no cell); the sweep/pitch production is delegated to [code] routines, so this stays [code].", cert: "code" },
  0x1c5d: { name: "requestSound6AndContinueInputScan", role: "[code] On folded input IN0|IN1 bits 2-3 (mask 0x0c), seeds sound-request selector 0x41df=6 (the value armSoundSequenceBySelector 0x1819 keys on to arm sound sequence 0x1ebd, gated on sound driver 0x4006 bit0), then falls through to armInputFlagAndDrawInputColumns (0x1c68) to continue the input-column scan.", cert: "code" },
  0x2055: { name: "drawAnimatedTileFigureAtPackedCoord", role: "[code] Draw-dispatch table entry 0 (jump table 0x203d, dispatched by loc_202c): maps the packed coordinate in A to its tilemap-VRAM cell (mapPackedCoordToVram 0x20e1), folds that coord into a frame-timer-animated 2-bit tile variant (computeTileVariantFromValueAndTimer 0x2104 vs frame counter 0x425f), then draws a 2x2 block when coord bit4 is set (mapper carry live-out) else a double-height glyph into VRAM; animated counterpart to sibling entry 0x205e (fixed tile).", cert: "code" },
  0x03f2: { name: "runStartScreenAndLaunchGame", role: "[code] Game-state-2 (post-credit 'press start') handler: run per-frame formation prep (advanceFormationSweepOscillator/summarizeFormationOccupancy), dispatch on SEQUENCE_STATE (0x400a) to one of four start-screen sub-handlers (resetObjectRamAndAdvanceSequence/holdStartLampsThenAdvanceSequence/blankVramRowsThenDriveStartLamps/driveStartButtonLamps), then tail-run beginGameOnStartButton to launch a 1-/2-player game on the start button.", cert: "code" },
  0x10e4: { name: "dispatchDeactivatedObjectAnim", role: "[code] Deactivated/dying-object animation sub-state dispatcher: read the object record's sub-state field (ix+2) and tail-dispatch via rst-28 (no continuation pushed) to the matching phase handler (armObjectAnimAndRequestSound/tickDeactivatedObjectAnim/endObjectAnimOnTimerExpiry/noopAnimDispatchSlot); the selected handler's own return returns to dispatchDeactivatedObjectAnim's caller.", cert: "code" },
  // spine-unblock leaves (loc_ names, [code] certs; understanding pending)
  0x0048: { name: "divideUnsigned8", role: "[code] 8-bit unsigned divide of A by D via 8 rounds of compare-subtract-shift (restoring divide, divisor walked down one bit per round): quotient in C, remainder in A, shifted divisor in D, round counter B spent to 0 -- pure register math, no memory effect", cert: "code" },
  0x0e2b: { name: "advanceObjectFlightAndFire", role: "[seen] Object-AI flight-state handler (RST-28 dispatch slot 3 @0x0ce6): each frame bumps the per-object counter (record+3) and runs advanceObjectFlightCurve, then folds the per-object increment (record+9) + curve heading hi (record+0x19) into a new screen Y (record+4); a too-high Y advances the dispatch state (record+2) by 2, a wrapped counter by 1; else, gated by OBJ_ACTIVE_FLAG bit0, aims the octant (aimObjectAtTarget) and -- when 0x422b bit0 clear -- scans the row table (0x4213) for the counter value, firing an aimed projectile (spawnAimedProjectileAtPlayer) on a match.", cert: "seen" },
  0x0faf: { name: "advanceHomingObjectFlightAndFire", role: "[code] Object-AI homing flight-state handler (RST-28 dispatch slot 9 @0x0ce6): like advanceObjectFlightAndFire but per the mode byte (record+0x17) first homes the column (record+9) toward the target column (0x4202) -- mode==4 on odd frame parity (0x425f bit0), mode>4 always, mode<4 never; screen Y (record+4)=column+curve heading; a too-high Y sets state 5, a wrapped counter sets state 4, else the move-throttle (record+0x10) advances state (dec) on expiry; otherwise, gated by OBJ_ACTIVE_FLAG bit0, aims (aimObjectAtTarget) and fires (spawnAimedProjectileAtPlayer) on a row-table (0x4213) match. Unreached in attract+1P captures.", cert: "code" },
  0x11b0: { name: "aimObjectAtTarget", role: "[seen] Aim an object at the target-X anchor: from the vertical drop (0xf0 - sprite Y, ix+3) and the horizontal delta (target-X 0x4202 - sprite X, ix+4) derive a direction octant via computeDirectionOctantFromSlope (computeDirectionOctantFromSlope), mirroring the octant for a left-of-target delta, and store it in the object's direction field (ix+5).", cert: "seen" },
  0x11d0: { name: "computeDirectionOctantFromSlope", role: "[seen] Turn a slope (dividend/divisor, divided via divideUnsigned8) into a 0-7 direction octant: clamp a top-bit-set (steepest) quotient to 0x80, return the top three bits as the octant in A. Consumed by aimObjectAtTarget (aimObjectAtTarget) as the object's stored heading.", cert: "seen" },
  0x11e0: { name: "spawnAimedProjectileAtPlayer", role: "[code] Claim the first free slot in the 14-entry projectile table at 0x4260 (stride 5, bit0 of entry[0]=active) and populate it from the IX object: entry[0]=active, entry[1]=sprite Y, entry[3]=sprite X, entry[4]=X velocity scaled toward the player-X reference 0x4202 (via computeJitteredXVelocity, mirrored when the target is to the left); no-op when the table is full. An aimed enemy shot at the player. Tail-called by advanceObjectFlightAndFire/advanceHomingObjectFlightAndFire on a firing-row match.", cert: "code" },
  0x1218: { name: "computeJitteredXVelocity", role: "[code] RNG-jittered slope scaler: divide dividend/divisor via divideUnsigned8, add a bounded PRNG draw (0..31, advanceRandomSeed/loc_003c) plus a floor of 6, and clamp to 0x7f on positive overflow; return the value in A. Its consumer spawnAimedProjectileAtPlayer stores it as a spawned object's scaled X velocity (0x4260 table entry[4], mirrored when left of target).", cert: "code" },
  0x16f5: { name: "driveSoundFrame", role: "[code] Sound-driver per-frame tick: clear the composite sound-flag byte (0x41c0) and prime SOUND_PITCH (0x41c1)=0xFF, run the seven channel/effect updaters in fixed ROM order, then latch the composed bytes -- composite -> SOUND_W_REG6 (0x6806), its rotate-right -> SOUND_W_REG7 (0x6807), pitch shadow -> SOUND_PITCH_W (0x7800)", cert: "code" },
  0x1c50: { name: "requestSoundOnInput1AndContinueScan", role: "[code] Read input port IN1 (0x6800); if either of its low two bits is set, seed the shared control/sound-request byte 0x41df=0x16; then tail-continue the input scan via requestSound6AndContinueInputScan (0x1c5d), handing it the caller's IN0 (B) and the full IN1 byte for the downstream IN0|IN1 bit tests", cert: "code" },
  // spine dispatcher + main-loop input step (loc_ names, [code] certs; understanding pending)
  0x0cd6: { name: "driveObjectSlot", role: "[code] Per-slot object driver: for one object record (IX), hands a dying object (record+1 bit0) to the death-animation dispatcher, skips an inactive slot (record+0 bit0 clear), else runs the object-AI handler selected by the record's state index (record+2, 0..15).", cert: "code" },
  0x1c3a: { name: "driveSoundFrameAndScanInput", role: "[code] Per-frame audio+input service (game-state A==1 branch of loc_1bcd): tick the sound driver (0x16f5) and the decaying sweep (0x16a6), pet the watchdog (read 0x7800), then read IN0 (0x6000) and, if any arm bit is set (mask 0x83 = bits 7/1/0), raise the pitch-ramp arm cell 0x41c9; falls through into the input-scan chain with the raw IN0.", cert: "code" },
  // object-spawn pipeline re-land (loc_ names, [code] certs; understanding pending)
  0x0cc3: { name: "driveAllObjectSlots", role: "[code] Per-frame driver of all 8 object slots (SPRITE_SOURCE_OBJ_BASE 0x42b0, 32-byte stride): calls driveObjectSlot on each record — dying-anim handoff, inactive skip, or the state-indexed AI handler — walking the record base across the eight slots.", cert: "code" },
  0x023f: { name: "activateDescriptorSlotsThenAdvanceSequence", role: "[seen] Sequence-state handler (rst-28 dispatch keyed on SEQUENCE_STATE): runs the 4 per-frame subsystem updates, then on the 0x4008 sub-timer's expiry activates a descriptor slot (via activateDescriptorSlot, descriptor number at 0x4009) and bumps DRAWN_COLUMN_COUNT, and on the 0x4009 dwell's expiry advances SEQUENCE_STATE.", cert: "seen" },
  0x0267: { name: "queueColumnDrawAndAdvanceSequence", role: "[seen] Sequence-state handler (rst-28 dispatch keyed on SEQUENCE_STATE): runs the 4 per-frame subsystem updates, then counts down the 0x4009 dwell; on expiry advances SEQUENCE_STATE, re-arms the 0x4008/0x4009 two-tier timer pair (0x40 sub / 0x11 dwell), bumps DRAWN_COLUMN_COUNT, and enqueues a channel-6 column-draw command word (arg 0x0f) via enqueueCommandWord.", cert: "seen" },
  0x028e: { name: "dwellThenAdvanceSequence", role: "[code] Sequence-state dwell handler (rst-28 dispatch target, SEQUENCE_STATE index 7 via loc_0156 table @0x0164): run the four shared per-frame subsystem updates (clearStridedTable, stageObjectsToSpriteShadow, driveObjectSlots loop 0x0cc3, redrawTileColumnsPeriodically), then tail-tick the prescaled sequence-dwell timer (tickPrescaledSequenceTimer 0x0336: sub-timer 0x4008 wrap reloads to 60 and cascades a tick into dwell tier 0x4009, carrying into SEQUENCE_STATE 0x400a on that tier's expiry); performs no staging side effect of its own -- a pure dwell state.", cert: "code" },
  0x0661: { name: "runGameplayFrameAndAdvanceOnFieldClear", role: "[code] Per-frame play pipeline (rst-28 dispatch target reached from three state tables: loc_0156 state 15 @0x0182, loc_0536 @0x054a, loc_077b @0x078f): run the 27 gameplay subsystem updates in fixed ROM order (player/shot move+stage, projectiles, object-AI loop 0x0cc3, sprite staging, collision flaggers, spawn/launch/pace, sound drivers, stage advance/reseed), then -- only while the play field is quiescent (no bit0 in 0x4208|0x4201|OBJ_ACTIVE_FLAG 0x4200, stage-advance flag 0x4225 bit0 set, no active sub-slot bit0 across the 14 five-byte records at 0x4260) -- decrement the sequence dwell timer 0x4009 and, on its zero-cross, advance SEQUENCE_STATE (0x400a).", cert: "code" },
};
